/* Generated by art/pipeline/install_unit_sprites.py from art/out/man_at_arms_v3/sprites@2x */
window.POCKET_EMPIRES_SPRITES = Object.assign(window.POCKET_EMPIRES_SPRITES || {}, {
 "man_at_arms": {
  "clips": [
   "idle",
   "walk"
  ],
  "dirs": 8,
  "group": "directional_unit",
  "key_format": "man_at_arms_<team>_<clip>_d<dir>[_<frame>]",
  "note": "direction k = camera yaw 45 + 45*k deg (counter-clockwise from above); d0 matches the single facing the existing 0 A.D. units were baked at",
  "pitch": 30.0,
  "teams": [
   "blue",
   "red"
  ],
  "yaw0": 45.0
 },
 "man_at_arms_blue_idle_d0": {
  "clip": "idle",
  "dir": 0,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d0_0.png",
   "man_at_arms_blue_idle_d0_1.png",
   "man_at_arms_blue_idle_d0_2.png",
   "man_at_arms_blue_idle_d0_3.png",
   "man_at_arms_blue_idle_d0_4.png",
   "man_at_arms_blue_idle_d0_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d0_0": {
  "file": "man_at_arms_blue_idle_d0_0.png",
  "fill": 0.173,
  "fp_cx": 63.3,
  "fp_cy": 122.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_1": {
  "file": "man_at_arms_blue_idle_d0_1.png",
  "fill": 0.1732,
  "fp_cx": 63.06,
  "fp_cy": 122.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_2": {
  "file": "man_at_arms_blue_idle_d0_2.png",
  "fill": 0.1728,
  "fp_cx": 62.88,
  "fp_cy": 122.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_3": {
  "file": "man_at_arms_blue_idle_d0_3.png",
  "fill": 0.1728,
  "fp_cx": 62.82,
  "fp_cy": 122.48,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_4": {
  "file": "man_at_arms_blue_idle_d0_4.png",
  "fill": 0.1728,
  "fp_cx": 62.88,
  "fp_cy": 122.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_5": {
  "file": "man_at_arms_blue_idle_d0_5.png",
  "fill": 0.173,
  "fp_cx": 63.06,
  "fp_cy": 122.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1": {
  "clip": "idle",
  "dir": 1,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d1_0.png",
   "man_at_arms_blue_idle_d1_1.png",
   "man_at_arms_blue_idle_d1_2.png",
   "man_at_arms_blue_idle_d1_3.png",
   "man_at_arms_blue_idle_d1_4.png",
   "man_at_arms_blue_idle_d1_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d1_0": {
  "file": "man_at_arms_blue_idle_d1_0.png",
  "fill": 0.1125,
  "fp_cx": 65.3,
  "fp_cy": 131.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_1": {
  "file": "man_at_arms_blue_idle_d1_1.png",
  "fill": 0.1127,
  "fp_cx": 64.98,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_2": {
  "file": "man_at_arms_blue_idle_d1_2.png",
  "fill": 0.1128,
  "fp_cx": 64.72,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_3": {
  "file": "man_at_arms_blue_idle_d1_3.png",
  "fill": 0.1132,
  "fp_cx": 64.62,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_4": {
  "file": "man_at_arms_blue_idle_d1_4.png",
  "fill": 0.1128,
  "fp_cx": 64.72,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_5": {
  "file": "man_at_arms_blue_idle_d1_5.png",
  "fill": 0.1127,
  "fp_cx": 64.98,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2": {
  "clip": "idle",
  "dir": 2,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d2_0.png",
   "man_at_arms_blue_idle_d2_1.png",
   "man_at_arms_blue_idle_d2_2.png",
   "man_at_arms_blue_idle_d2_3.png",
   "man_at_arms_blue_idle_d2_4.png",
   "man_at_arms_blue_idle_d2_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d2_0": {
  "file": "man_at_arms_blue_idle_d2_0.png",
  "fill": 0.1524,
  "fp_cx": 67.6,
  "fp_cy": 127.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_1": {
  "file": "man_at_arms_blue_idle_d2_1.png",
  "fill": 0.1526,
  "fp_cx": 67.38,
  "fp_cy": 127.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_2": {
  "file": "man_at_arms_blue_idle_d2_2.png",
  "fill": 0.1524,
  "fp_cx": 67.2,
  "fp_cy": 127.8,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_3": {
  "file": "man_at_arms_blue_idle_d2_3.png",
  "fill": 0.1516,
  "fp_cx": 67.12,
  "fp_cy": 127.82,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_4": {
  "file": "man_at_arms_blue_idle_d2_4.png",
  "fill": 0.1524,
  "fp_cx": 67.2,
  "fp_cy": 127.8,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_5": {
  "file": "man_at_arms_blue_idle_d2_5.png",
  "fill": 0.1526,
  "fp_cx": 67.38,
  "fp_cy": 127.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3": {
  "clip": "idle",
  "dir": 3,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d3_0.png",
   "man_at_arms_blue_idle_d3_1.png",
   "man_at_arms_blue_idle_d3_2.png",
   "man_at_arms_blue_idle_d3_3.png",
   "man_at_arms_blue_idle_d3_4.png",
   "man_at_arms_blue_idle_d3_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d3_0": {
  "file": "man_at_arms_blue_idle_d3_0.png",
  "fill": 0.196,
  "fp_cx": 82.98,
  "fp_cy": 126.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_1": {
  "file": "man_at_arms_blue_idle_d3_1.png",
  "fill": 0.1962,
  "fp_cx": 82.98,
  "fp_cy": 126.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_2": {
  "file": "man_at_arms_blue_idle_d3_2.png",
  "fill": 0.197,
  "fp_cx": 82.98,
  "fp_cy": 126.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_3": {
  "file": "man_at_arms_blue_idle_d3_3.png",
  "fill": 0.1971,
  "fp_cx": 82.98,
  "fp_cy": 126.92,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_4": {
  "file": "man_at_arms_blue_idle_d3_4.png",
  "fill": 0.197,
  "fp_cx": 82.98,
  "fp_cy": 126.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_5": {
  "file": "man_at_arms_blue_idle_d3_5.png",
  "fill": 0.1962,
  "fp_cx": 82.98,
  "fp_cy": 126.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4": {
  "clip": "idle",
  "dir": 4,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d4_0.png",
   "man_at_arms_blue_idle_d4_1.png",
   "man_at_arms_blue_idle_d4_2.png",
   "man_at_arms_blue_idle_d4_3.png",
   "man_at_arms_blue_idle_d4_4.png",
   "man_at_arms_blue_idle_d4_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d4_0": {
  "file": "man_at_arms_blue_idle_d4_0.png",
  "fill": 0.1651,
  "fp_cx": 80.7,
  "fp_cy": 125.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_1": {
  "file": "man_at_arms_blue_idle_d4_1.png",
  "fill": 0.1657,
  "fp_cx": 80.94,
  "fp_cy": 125.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_2": {
  "file": "man_at_arms_blue_idle_d4_2.png",
  "fill": 0.1671,
  "fp_cx": 81.12,
  "fp_cy": 125.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_3": {
  "file": "man_at_arms_blue_idle_d4_3.png",
  "fill": 0.1672,
  "fp_cx": 81.18,
  "fp_cy": 125.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_4": {
  "file": "man_at_arms_blue_idle_d4_4.png",
  "fill": 0.1671,
  "fp_cx": 81.12,
  "fp_cy": 125.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_5": {
  "file": "man_at_arms_blue_idle_d4_5.png",
  "fill": 0.1657,
  "fp_cx": 80.94,
  "fp_cy": 125.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5": {
  "clip": "idle",
  "dir": 5,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d5_0.png",
   "man_at_arms_blue_idle_d5_1.png",
   "man_at_arms_blue_idle_d5_2.png",
   "man_at_arms_blue_idle_d5_3.png",
   "man_at_arms_blue_idle_d5_4.png",
   "man_at_arms_blue_idle_d5_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d5_0": {
  "file": "man_at_arms_blue_idle_d5_0.png",
  "fill": 0.113,
  "fp_cx": 78.7,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_1": {
  "file": "man_at_arms_blue_idle_d5_1.png",
  "fill": 0.1132,
  "fp_cx": 79.02,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_2": {
  "file": "man_at_arms_blue_idle_d5_2.png",
  "fill": 0.1134,
  "fp_cx": 79.28,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_3": {
  "file": "man_at_arms_blue_idle_d5_3.png",
  "fill": 0.1136,
  "fp_cx": 79.38,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_4": {
  "file": "man_at_arms_blue_idle_d5_4.png",
  "fill": 0.1134,
  "fp_cx": 79.28,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_5": {
  "file": "man_at_arms_blue_idle_d5_5.png",
  "fill": 0.1132,
  "fp_cx": 79.02,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6": {
  "clip": "idle",
  "dir": 6,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d6_0.png",
   "man_at_arms_blue_idle_d6_1.png",
   "man_at_arms_blue_idle_d6_2.png",
   "man_at_arms_blue_idle_d6_3.png",
   "man_at_arms_blue_idle_d6_4.png",
   "man_at_arms_blue_idle_d6_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d6_0": {
  "file": "man_at_arms_blue_idle_d6_0.png",
  "fill": 0.1636,
  "fp_cx": 76.4,
  "fp_cy": 120.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_1": {
  "file": "man_at_arms_blue_idle_d6_1.png",
  "fill": 0.162,
  "fp_cx": 76.62,
  "fp_cy": 120.4,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_2": {
  "file": "man_at_arms_blue_idle_d6_2.png",
  "fill": 0.1607,
  "fp_cx": 76.8,
  "fp_cy": 120.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_3": {
  "file": "man_at_arms_blue_idle_d6_3.png",
  "fill": 0.1605,
  "fp_cx": 76.88,
  "fp_cy": 120.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_4": {
  "file": "man_at_arms_blue_idle_d6_4.png",
  "fill": 0.1609,
  "fp_cx": 76.8,
  "fp_cy": 120.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_5": {
  "file": "man_at_arms_blue_idle_d6_5.png",
  "fill": 0.1622,
  "fp_cx": 76.62,
  "fp_cy": 120.4,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7": {
  "clip": "idle",
  "dir": 7,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d7_0.png",
   "man_at_arms_blue_idle_d7_1.png",
   "man_at_arms_blue_idle_d7_2.png",
   "man_at_arms_blue_idle_d7_3.png",
   "man_at_arms_blue_idle_d7_4.png",
   "man_at_arms_blue_idle_d7_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d7_0": {
  "file": "man_at_arms_blue_idle_d7_0.png",
  "fill": 0.2,
  "fp_cx": 61.02,
  "fp_cy": 121.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_1": {
  "file": "man_at_arms_blue_idle_d7_1.png",
  "fill": 0.1987,
  "fp_cx": 61.02,
  "fp_cy": 121.36,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_2": {
  "file": "man_at_arms_blue_idle_d7_2.png",
  "fill": 0.1981,
  "fp_cx": 61.02,
  "fp_cy": 121.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_3": {
  "file": "man_at_arms_blue_idle_d7_3.png",
  "fill": 0.1977,
  "fp_cx": 61.02,
  "fp_cy": 121.18,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_4": {
  "file": "man_at_arms_blue_idle_d7_4.png",
  "fill": 0.1977,
  "fp_cx": 61.02,
  "fp_cy": 121.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_5": {
  "file": "man_at_arms_blue_idle_d7_5.png",
  "fill": 0.1985,
  "fp_cx": 61.02,
  "fp_cy": 121.36,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0": {
  "clip": "walk",
  "dir": 0,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d0_0.png",
   "man_at_arms_blue_walk_d0_1.png",
   "man_at_arms_blue_walk_d0_2.png",
   "man_at_arms_blue_walk_d0_3.png",
   "man_at_arms_blue_walk_d0_4.png",
   "man_at_arms_blue_walk_d0_5.png",
   "man_at_arms_blue_walk_d0_6.png",
   "man_at_arms_blue_walk_d0_7.png",
   "man_at_arms_blue_walk_d0_8.png",
   "man_at_arms_blue_walk_d0_9.png",
   "man_at_arms_blue_walk_d0_10.png",
   "man_at_arms_blue_walk_d0_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d0_0": {
  "file": "man_at_arms_blue_walk_d0_0.png",
  "fill": 0.1622,
  "fp_cx": 67.94,
  "fp_cy": 124.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_1": {
  "file": "man_at_arms_blue_walk_d0_1.png",
  "fill": 0.1599,
  "fp_cx": 65.12,
  "fp_cy": 123.2,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_10": {
  "file": "man_at_arms_blue_walk_d0_10.png",
  "fill": 0.1572,
  "fp_cx": 71.26,
  "fp_cy": 126.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_11": {
  "file": "man_at_arms_blue_walk_d0_11.png",
  "fill": 0.1638,
  "fp_cx": 71.66,
  "fp_cy": 126.46,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_2": {
  "file": "man_at_arms_blue_walk_d0_2.png",
  "fill": 0.1574,
  "fp_cx": 64.82,
  "fp_cy": 123.16,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_3": {
  "file": "man_at_arms_blue_walk_d0_3.png",
  "fill": 0.1601,
  "fp_cx": 68.7,
  "fp_cy": 125.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_4": {
  "file": "man_at_arms_blue_walk_d0_4.png",
  "fill": 0.1609,
  "fp_cx": 70.88,
  "fp_cy": 126.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_5": {
  "file": "man_at_arms_blue_walk_d0_5.png",
  "fill": 0.1584,
  "fp_cx": 71.04,
  "fp_cy": 126.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_6": {
  "file": "man_at_arms_blue_walk_d0_6.png",
  "fill": 0.1537,
  "fp_cx": 67.22,
  "fp_cy": 124.84,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_7": {
  "file": "man_at_arms_blue_walk_d0_7.png",
  "fill": 0.1568,
  "fp_cx": 64.5,
  "fp_cy": 123.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_8": {
  "file": "man_at_arms_blue_walk_d0_8.png",
  "fill": 0.1618,
  "fp_cx": 64.48,
  "fp_cy": 123.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_9": {
  "file": "man_at_arms_blue_walk_d0_9.png",
  "fill": 0.1599,
  "fp_cx": 68.76,
  "fp_cy": 125.3,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1": {
  "clip": "walk",
  "dir": 1,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d1_0.png",
   "man_at_arms_blue_walk_d1_1.png",
   "man_at_arms_blue_walk_d1_2.png",
   "man_at_arms_blue_walk_d1_3.png",
   "man_at_arms_blue_walk_d1_4.png",
   "man_at_arms_blue_walk_d1_5.png",
   "man_at_arms_blue_walk_d1_6.png",
   "man_at_arms_blue_walk_d1_7.png",
   "man_at_arms_blue_walk_d1_8.png",
   "man_at_arms_blue_walk_d1_9.png",
   "man_at_arms_blue_walk_d1_10.png",
   "man_at_arms_blue_walk_d1_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d1_0": {
  "file": "man_at_arms_blue_walk_d1_0.png",
  "fill": 0.1339,
  "fp_cx": 71.2,
  "fp_cy": 131.1,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_1": {
  "file": "man_at_arms_blue_walk_d1_1.png",
  "fill": 0.1304,
  "fp_cx": 67.28,
  "fp_cy": 131.14,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_10": {
  "file": "man_at_arms_blue_walk_d1_10.png",
  "fill": 0.1248,
  "fp_cx": 76.12,
  "fp_cy": 131.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_11": {
  "file": "man_at_arms_blue_walk_d1_11.png",
  "fill": 0.1306,
  "fp_cx": 76.52,
  "fp_cy": 131.14,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_2": {
  "file": "man_at_arms_blue_walk_d1_2.png",
  "fill": 0.1159,
  "fp_cx": 67.02,
  "fp_cy": 131.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_3": {
  "file": "man_at_arms_blue_walk_d1_3.png",
  "fill": 0.1086,
  "fp_cx": 72.74,
  "fp_cy": 131.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_4": {
  "file": "man_at_arms_blue_walk_d1_4.png",
  "fill": 0.1244,
  "fp_cx": 76.04,
  "fp_cy": 131.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_5": {
  "file": "man_at_arms_blue_walk_d1_5.png",
  "fill": 0.1269,
  "fp_cx": 76.42,
  "fp_cy": 131.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_6": {
  "file": "man_at_arms_blue_walk_d1_6.png",
  "fill": 0.1296,
  "fp_cx": 71.1,
  "fp_cy": 131.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_7": {
  "file": "man_at_arms_blue_walk_d1_7.png",
  "fill": 0.125,
  "fp_cx": 67.2,
  "fp_cy": 131.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_8": {
  "file": "man_at_arms_blue_walk_d1_8.png",
  "fill": 0.1157,
  "fp_cx": 67.0,
  "fp_cy": 131.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_9": {
  "file": "man_at_arms_blue_walk_d1_9.png",
  "fill": 0.1073,
  "fp_cx": 72.82,
  "fp_cy": 131.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2": {
  "clip": "walk",
  "dir": 2,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d2_0.png",
   "man_at_arms_blue_walk_d2_1.png",
   "man_at_arms_blue_walk_d2_2.png",
   "man_at_arms_blue_walk_d2_3.png",
   "man_at_arms_blue_walk_d2_4.png",
   "man_at_arms_blue_walk_d2_5.png",
   "man_at_arms_blue_walk_d2_6.png",
   "man_at_arms_blue_walk_d2_7.png",
   "man_at_arms_blue_walk_d2_8.png",
   "man_at_arms_blue_walk_d2_9.png",
   "man_at_arms_blue_walk_d2_10.png",
   "man_at_arms_blue_walk_d2_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d2_0": {
  "file": "man_at_arms_blue_walk_d2_0.png",
  "fill": 0.1534,
  "fp_cx": 71.32,
  "fp_cy": 125.26,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_1": {
  "file": "man_at_arms_blue_walk_d2_1.png",
  "fill": 0.1512,
  "fp_cx": 68.58,
  "fp_cy": 126.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_10": {
  "file": "man_at_arms_blue_walk_d2_10.png",
  "fill": 0.1561,
  "fp_cx": 74.96,
  "fp_cy": 123.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_11": {
  "file": "man_at_arms_blue_walk_d2_11.png",
  "fill": 0.1539,
  "fp_cx": 75.12,
  "fp_cy": 123.4,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_2": {
  "file": "man_at_arms_blue_walk_d2_2.png",
  "fill": 0.1487,
  "fp_cx": 68.52,
  "fp_cy": 126.82,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_3": {
  "file": "man_at_arms_blue_walk_d2_3.png",
  "fill": 0.1584,
  "fp_cx": 72.72,
  "fp_cy": 124.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_4": {
  "file": "man_at_arms_blue_walk_d2_4.png",
  "fill": 0.1568,
  "fp_cx": 75.22,
  "fp_cy": 123.8,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_5": {
  "file": "man_at_arms_blue_walk_d2_5.png",
  "fill": 0.1686,
  "fp_cx": 75.6,
  "fp_cy": 123.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_6": {
  "file": "man_at_arms_blue_walk_d2_6.png",
  "fill": 0.1696,
  "fp_cx": 71.88,
  "fp_cy": 125.62,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_7": {
  "file": "man_at_arms_blue_walk_d2_7.png",
  "fill": 0.1603,
  "fp_cx": 69.06,
  "fp_cy": 126.98,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_8": {
  "file": "man_at_arms_blue_walk_d2_8.png",
  "fill": 0.152,
  "fp_cx": 68.82,
  "fp_cy": 127.0,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_9": {
  "file": "man_at_arms_blue_walk_d2_9.png",
  "fill": 0.1541,
  "fp_cx": 72.78,
  "fp_cy": 124.86,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3": {
  "clip": "walk",
  "dir": 3,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d3_0.png",
   "man_at_arms_blue_walk_d3_1.png",
   "man_at_arms_blue_walk_d3_2.png",
   "man_at_arms_blue_walk_d3_3.png",
   "man_at_arms_blue_walk_d3_4.png",
   "man_at_arms_blue_walk_d3_5.png",
   "man_at_arms_blue_walk_d3_6.png",
   "man_at_arms_blue_walk_d3_7.png",
   "man_at_arms_blue_walk_d3_8.png",
   "man_at_arms_blue_walk_d3_9.png",
   "man_at_arms_blue_walk_d3_10.png",
   "man_at_arms_blue_walk_d3_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d3_0": {
  "file": "man_at_arms_blue_walk_d3_0.png",
  "fill": 0.1784,
  "fp_cx": 82.32,
  "fp_cy": 123.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_1": {
  "file": "man_at_arms_blue_walk_d3_1.png",
  "fill": 0.1809,
  "fp_cx": 82.38,
  "fp_cy": 125.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_10": {
  "file": "man_at_arms_blue_walk_d3_10.png",
  "fill": 0.1871,
  "fp_cx": 82.56,
  "fp_cy": 121.18,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_11": {
  "file": "man_at_arms_blue_walk_d3_11.png",
  "fill": 0.1806,
  "fp_cx": 82.38,
  "fp_cy": 120.98,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_2": {
  "file": "man_at_arms_blue_walk_d3_2.png",
  "fill": 0.1804,
  "fp_cx": 82.56,
  "fp_cy": 125.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_3": {
  "file": "man_at_arms_blue_walk_d3_3.png",
  "fill": 0.1819,
  "fp_cx": 82.78,
  "fp_cy": 122.86,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_4": {
  "file": "man_at_arms_blue_walk_d3_4.png",
  "fill": 0.1829,
  "fp_cx": 83.0,
  "fp_cy": 121.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_5": {
  "file": "man_at_arms_blue_walk_d3_5.png",
  "fill": 0.1775,
  "fp_cx": 83.16,
  "fp_cy": 121.02,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_6": {
  "file": "man_at_arms_blue_walk_d3_6.png",
  "fill": 0.1759,
  "fp_cx": 83.22,
  "fp_cy": 123.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_7": {
  "file": "man_at_arms_blue_walk_d3_7.png",
  "fill": 0.1765,
  "fp_cx": 83.16,
  "fp_cy": 125.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_8": {
  "file": "man_at_arms_blue_walk_d3_8.png",
  "fill": 0.1765,
  "fp_cx": 83.0,
  "fp_cy": 125.74,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_9": {
  "file": "man_at_arms_blue_walk_d3_9.png",
  "fill": 0.1829,
  "fp_cx": 82.78,
  "fp_cy": 122.82,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4": {
  "clip": "walk",
  "dir": 4,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d4_0.png",
   "man_at_arms_blue_walk_d4_1.png",
   "man_at_arms_blue_walk_d4_2.png",
   "man_at_arms_blue_walk_d4_3.png",
   "man_at_arms_blue_walk_d4_4.png",
   "man_at_arms_blue_walk_d4_5.png",
   "man_at_arms_blue_walk_d4_6.png",
   "man_at_arms_blue_walk_d4_7.png",
   "man_at_arms_blue_walk_d4_8.png",
   "man_at_arms_blue_walk_d4_9.png",
   "man_at_arms_blue_walk_d4_10.png",
   "man_at_arms_blue_walk_d4_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d4_0": {
  "file": "man_at_arms_blue_walk_d4_0.png",
  "fill": 0.1485,
  "fp_cx": 76.06,
  "fp_cy": 123.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_1": {
  "file": "man_at_arms_blue_walk_d4_1.png",
  "fill": 0.142,
  "fp_cx": 78.88,
  "fp_cy": 124.96,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_10": {
  "file": "man_at_arms_blue_walk_d4_10.png",
  "fill": 0.1458,
  "fp_cx": 72.74,
  "fp_cy": 121.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_11": {
  "file": "man_at_arms_blue_walk_d4_11.png",
  "fill": 0.1522,
  "fp_cx": 72.34,
  "fp_cy": 121.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_2": {
  "file": "man_at_arms_blue_walk_d4_2.png",
  "fill": 0.1352,
  "fp_cx": 79.18,
  "fp_cy": 125.0,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_3": {
  "file": "man_at_arms_blue_walk_d4_3.png",
  "fill": 0.1402,
  "fp_cx": 75.3,
  "fp_cy": 122.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_4": {
  "file": "man_at_arms_blue_walk_d4_4.png",
  "fill": 0.141,
  "fp_cx": 73.12,
  "fp_cy": 121.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_5": {
  "file": "man_at_arms_blue_walk_d4_5.png",
  "fill": 0.1341,
  "fp_cx": 72.96,
  "fp_cy": 121.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_6": {
  "file": "man_at_arms_blue_walk_d4_6.png",
  "fill": 0.1325,
  "fp_cx": 76.78,
  "fp_cy": 123.3,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_7": {
  "file": "man_at_arms_blue_walk_d4_7.png",
  "fill": 0.1304,
  "fp_cx": 79.5,
  "fp_cy": 124.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_8": {
  "file": "man_at_arms_blue_walk_d4_8.png",
  "fill": 0.1346,
  "fp_cx": 79.52,
  "fp_cy": 124.84,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_9": {
  "file": "man_at_arms_blue_walk_d4_9.png",
  "fill": 0.1424,
  "fp_cx": 75.24,
  "fp_cy": 122.86,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5": {
  "clip": "walk",
  "dir": 5,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d5_0.png",
   "man_at_arms_blue_walk_d5_1.png",
   "man_at_arms_blue_walk_d5_2.png",
   "man_at_arms_blue_walk_d5_3.png",
   "man_at_arms_blue_walk_d5_4.png",
   "man_at_arms_blue_walk_d5_5.png",
   "man_at_arms_blue_walk_d5_6.png",
   "man_at_arms_blue_walk_d5_7.png",
   "man_at_arms_blue_walk_d5_8.png",
   "man_at_arms_blue_walk_d5_9.png",
   "man_at_arms_blue_walk_d5_10.png",
   "man_at_arms_blue_walk_d5_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d5_0": {
  "file": "man_at_arms_blue_walk_d5_0.png",
  "fill": 0.1481,
  "fp_cx": 72.8,
  "fp_cy": 129.0,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_1": {
  "file": "man_at_arms_blue_walk_d5_1.png",
  "fill": 0.1408,
  "fp_cx": 76.72,
  "fp_cy": 128.96,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_10": {
  "file": "man_at_arms_blue_walk_d5_10.png",
  "fill": 0.1343,
  "fp_cx": 67.88,
  "fp_cy": 128.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_11": {
  "file": "man_at_arms_blue_walk_d5_11.png",
  "fill": 0.1456,
  "fp_cx": 67.48,
  "fp_cy": 128.96,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_2": {
  "file": "man_at_arms_blue_walk_d5_2.png",
  "fill": 0.1169,
  "fp_cx": 76.98,
  "fp_cy": 128.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_3": {
  "file": "man_at_arms_blue_walk_d5_3.png",
  "fill": 0.1071,
  "fp_cx": 71.26,
  "fp_cy": 128.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_4": {
  "file": "man_at_arms_blue_walk_d5_4.png",
  "fill": 0.1356,
  "fp_cx": 67.96,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_5": {
  "file": "man_at_arms_blue_walk_d5_5.png",
  "fill": 0.1426,
  "fp_cx": 67.58,
  "fp_cy": 128.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_6": {
  "file": "man_at_arms_blue_walk_d5_6.png",
  "fill": 0.1437,
  "fp_cx": 72.9,
  "fp_cy": 128.54,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_7": {
  "file": "man_at_arms_blue_walk_d5_7.png",
  "fill": 0.1385,
  "fp_cx": 76.8,
  "fp_cy": 128.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_8": {
  "file": "man_at_arms_blue_walk_d5_8.png",
  "fill": 0.1219,
  "fp_cx": 77.0,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_9": {
  "file": "man_at_arms_blue_walk_d5_9.png",
  "fill": 0.1115,
  "fp_cx": 71.18,
  "fp_cy": 128.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6": {
  "clip": "walk",
  "dir": 6,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d6_0.png",
   "man_at_arms_blue_walk_d6_1.png",
   "man_at_arms_blue_walk_d6_2.png",
   "man_at_arms_blue_walk_d6_3.png",
   "man_at_arms_blue_walk_d6_4.png",
   "man_at_arms_blue_walk_d6_5.png",
   "man_at_arms_blue_walk_d6_6.png",
   "man_at_arms_blue_walk_d6_7.png",
   "man_at_arms_blue_walk_d6_8.png",
   "man_at_arms_blue_walk_d6_9.png",
   "man_at_arms_blue_walk_d6_10.png",
   "man_at_arms_blue_walk_d6_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d6_0": {
  "file": "man_at_arms_blue_walk_d6_0.png",
  "fill": 0.1611,
  "fp_cx": 72.68,
  "fp_cy": 122.84,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_1": {
  "file": "man_at_arms_blue_walk_d6_1.png",
  "fill": 0.1605,
  "fp_cx": 75.42,
  "fp_cy": 121.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_10": {
  "file": "man_at_arms_blue_walk_d6_10.png",
  "fill": 0.1645,
  "fp_cx": 69.04,
  "fp_cy": 124.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_11": {
  "file": "man_at_arms_blue_walk_d6_11.png",
  "fill": 0.1622,
  "fp_cx": 68.88,
  "fp_cy": 124.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_2": {
  "file": "man_at_arms_blue_walk_d6_2.png",
  "fill": 0.1651,
  "fp_cx": 75.48,
  "fp_cy": 121.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_3": {
  "file": "man_at_arms_blue_walk_d6_3.png",
  "fill": 0.1775,
  "fp_cx": 71.28,
  "fp_cy": 123.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_4": {
  "file": "man_at_arms_blue_walk_d6_4.png",
  "fill": 0.1779,
  "fp_cx": 68.78,
  "fp_cy": 124.3,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_5": {
  "file": "man_at_arms_blue_walk_d6_5.png",
  "fill": 0.1773,
  "fp_cx": 68.4,
  "fp_cy": 124.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_6": {
  "file": "man_at_arms_blue_walk_d6_6.png",
  "fill": 0.1755,
  "fp_cx": 72.12,
  "fp_cy": 122.48,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_7": {
  "file": "man_at_arms_blue_walk_d6_7.png",
  "fill": 0.1748,
  "fp_cx": 74.94,
  "fp_cy": 121.12,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_8": {
  "file": "man_at_arms_blue_walk_d6_8.png",
  "fill": 0.1755,
  "fp_cx": 75.18,
  "fp_cy": 121.1,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_9": {
  "file": "man_at_arms_blue_walk_d6_9.png",
  "fill": 0.1752,
  "fp_cx": 71.22,
  "fp_cy": 123.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7": {
  "clip": "walk",
  "dir": 7,
  "duration": 1.1667,
  "files": [
   "man_at_arms_blue_walk_d7_0.png",
   "man_at_arms_blue_walk_d7_1.png",
   "man_at_arms_blue_walk_d7_2.png",
   "man_at_arms_blue_walk_d7_3.png",
   "man_at_arms_blue_walk_d7_4.png",
   "man_at_arms_blue_walk_d7_5.png",
   "man_at_arms_blue_walk_d7_6.png",
   "man_at_arms_blue_walk_d7_7.png",
   "man_at_arms_blue_walk_d7_8.png",
   "man_at_arms_blue_walk_d7_9.png",
   "man_at_arms_blue_walk_d7_10.png",
   "man_at_arms_blue_walk_d7_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d7_0": {
  "file": "man_at_arms_blue_walk_d7_0.png",
  "fill": 0.1896,
  "fp_cx": 61.68,
  "fp_cy": 124.48,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_1": {
  "file": "man_at_arms_blue_walk_d7_1.png",
  "fill": 0.189,
  "fp_cx": 61.62,
  "fp_cy": 122.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_10": {
  "file": "man_at_arms_blue_walk_d7_10.png",
  "fill": 0.1975,
  "fp_cx": 61.44,
  "fp_cy": 126.94,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_11": {
  "file": "man_at_arms_blue_walk_d7_11.png",
  "fill": 0.1923,
  "fp_cx": 61.62,
  "fp_cy": 127.14,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_2": {
  "file": "man_at_arms_blue_walk_d7_2.png",
  "fill": 0.1919,
  "fp_cx": 61.44,
  "fp_cy": 122.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_3": {
  "file": "man_at_arms_blue_walk_d7_3.png",
  "fill": 0.1971,
  "fp_cx": 61.22,
  "fp_cy": 125.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_4": {
  "file": "man_at_arms_blue_walk_d7_4.png",
  "fill": 0.202,
  "fp_cx": 61.0,
  "fp_cy": 126.9,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_5": {
  "file": "man_at_arms_blue_walk_d7_5.png",
  "fill": 0.1937,
  "fp_cx": 60.84,
  "fp_cy": 127.08,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_6": {
  "file": "man_at_arms_blue_walk_d7_6.png",
  "fill": 0.1894,
  "fp_cx": 60.78,
  "fp_cy": 124.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_7": {
  "file": "man_at_arms_blue_walk_d7_7.png",
  "fill": 0.1927,
  "fp_cx": 60.84,
  "fp_cy": 122.46,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_8": {
  "file": "man_at_arms_blue_walk_d7_8.png",
  "fill": 0.1964,
  "fp_cx": 61.0,
  "fp_cy": 122.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_9": {
  "file": "man_at_arms_blue_walk_d7_9.png",
  "fill": 0.1968,
  "fp_cx": 61.22,
  "fp_cy": 125.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0": {
  "clip": "idle",
  "dir": 0,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d0_0.png",
   "man_at_arms_red_idle_d0_1.png",
   "man_at_arms_red_idle_d0_2.png",
   "man_at_arms_red_idle_d0_3.png",
   "man_at_arms_red_idle_d0_4.png",
   "man_at_arms_red_idle_d0_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d0_0": {
  "file": "man_at_arms_red_idle_d0_0.png",
  "fill": 0.173,
  "fp_cx": 63.3,
  "fp_cy": 122.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_1": {
  "file": "man_at_arms_red_idle_d0_1.png",
  "fill": 0.1732,
  "fp_cx": 63.06,
  "fp_cy": 122.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_2": {
  "file": "man_at_arms_red_idle_d0_2.png",
  "fill": 0.1728,
  "fp_cx": 62.88,
  "fp_cy": 122.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_3": {
  "file": "man_at_arms_red_idle_d0_3.png",
  "fill": 0.1728,
  "fp_cx": 62.82,
  "fp_cy": 122.48,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_4": {
  "file": "man_at_arms_red_idle_d0_4.png",
  "fill": 0.1728,
  "fp_cx": 62.88,
  "fp_cy": 122.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_5": {
  "file": "man_at_arms_red_idle_d0_5.png",
  "fill": 0.173,
  "fp_cx": 63.06,
  "fp_cy": 122.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1": {
  "clip": "idle",
  "dir": 1,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d1_0.png",
   "man_at_arms_red_idle_d1_1.png",
   "man_at_arms_red_idle_d1_2.png",
   "man_at_arms_red_idle_d1_3.png",
   "man_at_arms_red_idle_d1_4.png",
   "man_at_arms_red_idle_d1_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d1_0": {
  "file": "man_at_arms_red_idle_d1_0.png",
  "fill": 0.1125,
  "fp_cx": 65.3,
  "fp_cy": 131.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_1": {
  "file": "man_at_arms_red_idle_d1_1.png",
  "fill": 0.1127,
  "fp_cx": 64.98,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_2": {
  "file": "man_at_arms_red_idle_d1_2.png",
  "fill": 0.1128,
  "fp_cx": 64.72,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_3": {
  "file": "man_at_arms_red_idle_d1_3.png",
  "fill": 0.1132,
  "fp_cx": 64.62,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_4": {
  "file": "man_at_arms_red_idle_d1_4.png",
  "fill": 0.1128,
  "fp_cx": 64.72,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_5": {
  "file": "man_at_arms_red_idle_d1_5.png",
  "fill": 0.1127,
  "fp_cx": 64.98,
  "fp_cy": 131.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2": {
  "clip": "idle",
  "dir": 2,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d2_0.png",
   "man_at_arms_red_idle_d2_1.png",
   "man_at_arms_red_idle_d2_2.png",
   "man_at_arms_red_idle_d2_3.png",
   "man_at_arms_red_idle_d2_4.png",
   "man_at_arms_red_idle_d2_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d2_0": {
  "file": "man_at_arms_red_idle_d2_0.png",
  "fill": 0.1524,
  "fp_cx": 67.6,
  "fp_cy": 127.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_1": {
  "file": "man_at_arms_red_idle_d2_1.png",
  "fill": 0.1526,
  "fp_cx": 67.38,
  "fp_cy": 127.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_2": {
  "file": "man_at_arms_red_idle_d2_2.png",
  "fill": 0.1524,
  "fp_cx": 67.2,
  "fp_cy": 127.8,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_3": {
  "file": "man_at_arms_red_idle_d2_3.png",
  "fill": 0.1516,
  "fp_cx": 67.12,
  "fp_cy": 127.82,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_4": {
  "file": "man_at_arms_red_idle_d2_4.png",
  "fill": 0.1524,
  "fp_cx": 67.2,
  "fp_cy": 127.8,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_5": {
  "file": "man_at_arms_red_idle_d2_5.png",
  "fill": 0.1526,
  "fp_cx": 67.38,
  "fp_cy": 127.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3": {
  "clip": "idle",
  "dir": 3,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d3_0.png",
   "man_at_arms_red_idle_d3_1.png",
   "man_at_arms_red_idle_d3_2.png",
   "man_at_arms_red_idle_d3_3.png",
   "man_at_arms_red_idle_d3_4.png",
   "man_at_arms_red_idle_d3_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d3_0": {
  "file": "man_at_arms_red_idle_d3_0.png",
  "fill": 0.196,
  "fp_cx": 82.98,
  "fp_cy": 126.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_1": {
  "file": "man_at_arms_red_idle_d3_1.png",
  "fill": 0.1962,
  "fp_cx": 82.98,
  "fp_cy": 126.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_2": {
  "file": "man_at_arms_red_idle_d3_2.png",
  "fill": 0.197,
  "fp_cx": 82.98,
  "fp_cy": 126.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_3": {
  "file": "man_at_arms_red_idle_d3_3.png",
  "fill": 0.1971,
  "fp_cx": 82.98,
  "fp_cy": 126.92,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_4": {
  "file": "man_at_arms_red_idle_d3_4.png",
  "fill": 0.197,
  "fp_cx": 82.98,
  "fp_cy": 126.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_5": {
  "file": "man_at_arms_red_idle_d3_5.png",
  "fill": 0.1962,
  "fp_cx": 82.98,
  "fp_cy": 126.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4": {
  "clip": "idle",
  "dir": 4,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d4_0.png",
   "man_at_arms_red_idle_d4_1.png",
   "man_at_arms_red_idle_d4_2.png",
   "man_at_arms_red_idle_d4_3.png",
   "man_at_arms_red_idle_d4_4.png",
   "man_at_arms_red_idle_d4_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d4_0": {
  "file": "man_at_arms_red_idle_d4_0.png",
  "fill": 0.1651,
  "fp_cx": 80.7,
  "fp_cy": 125.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_1": {
  "file": "man_at_arms_red_idle_d4_1.png",
  "fill": 0.1657,
  "fp_cx": 80.94,
  "fp_cy": 125.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_2": {
  "file": "man_at_arms_red_idle_d4_2.png",
  "fill": 0.1671,
  "fp_cx": 81.12,
  "fp_cy": 125.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_3": {
  "file": "man_at_arms_red_idle_d4_3.png",
  "fill": 0.1671,
  "fp_cx": 81.18,
  "fp_cy": 125.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_4": {
  "file": "man_at_arms_red_idle_d4_4.png",
  "fill": 0.1671,
  "fp_cx": 81.12,
  "fp_cy": 125.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_5": {
  "file": "man_at_arms_red_idle_d4_5.png",
  "fill": 0.1657,
  "fp_cx": 80.94,
  "fp_cy": 125.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5": {
  "clip": "idle",
  "dir": 5,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d5_0.png",
   "man_at_arms_red_idle_d5_1.png",
   "man_at_arms_red_idle_d5_2.png",
   "man_at_arms_red_idle_d5_3.png",
   "man_at_arms_red_idle_d5_4.png",
   "man_at_arms_red_idle_d5_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d5_0": {
  "file": "man_at_arms_red_idle_d5_0.png",
  "fill": 0.113,
  "fp_cx": 78.7,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_1": {
  "file": "man_at_arms_red_idle_d5_1.png",
  "fill": 0.1132,
  "fp_cx": 79.02,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_2": {
  "file": "man_at_arms_red_idle_d5_2.png",
  "fill": 0.1134,
  "fp_cx": 79.28,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_3": {
  "file": "man_at_arms_red_idle_d5_3.png",
  "fill": 0.1136,
  "fp_cx": 79.38,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_4": {
  "file": "man_at_arms_red_idle_d5_4.png",
  "fill": 0.1134,
  "fp_cx": 79.28,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_5": {
  "file": "man_at_arms_red_idle_d5_5.png",
  "fill": 0.1132,
  "fp_cx": 79.02,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6": {
  "clip": "idle",
  "dir": 6,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d6_0.png",
   "man_at_arms_red_idle_d6_1.png",
   "man_at_arms_red_idle_d6_2.png",
   "man_at_arms_red_idle_d6_3.png",
   "man_at_arms_red_idle_d6_4.png",
   "man_at_arms_red_idle_d6_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d6_0": {
  "file": "man_at_arms_red_idle_d6_0.png",
  "fill": 0.1636,
  "fp_cx": 76.4,
  "fp_cy": 120.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_1": {
  "file": "man_at_arms_red_idle_d6_1.png",
  "fill": 0.162,
  "fp_cx": 76.62,
  "fp_cy": 120.4,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_2": {
  "file": "man_at_arms_red_idle_d6_2.png",
  "fill": 0.1607,
  "fp_cx": 76.8,
  "fp_cy": 120.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_3": {
  "file": "man_at_arms_red_idle_d6_3.png",
  "fill": 0.1607,
  "fp_cx": 76.88,
  "fp_cy": 120.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_4": {
  "file": "man_at_arms_red_idle_d6_4.png",
  "fill": 0.1607,
  "fp_cx": 76.8,
  "fp_cy": 120.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_5": {
  "file": "man_at_arms_red_idle_d6_5.png",
  "fill": 0.1622,
  "fp_cx": 76.62,
  "fp_cy": 120.4,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7": {
  "clip": "idle",
  "dir": 7,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d7_0.png",
   "man_at_arms_red_idle_d7_1.png",
   "man_at_arms_red_idle_d7_2.png",
   "man_at_arms_red_idle_d7_3.png",
   "man_at_arms_red_idle_d7_4.png",
   "man_at_arms_red_idle_d7_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d7_0": {
  "file": "man_at_arms_red_idle_d7_0.png",
  "fill": 0.2,
  "fp_cx": 61.02,
  "fp_cy": 121.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_1": {
  "file": "man_at_arms_red_idle_d7_1.png",
  "fill": 0.1987,
  "fp_cx": 61.02,
  "fp_cy": 121.36,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_2": {
  "file": "man_at_arms_red_idle_d7_2.png",
  "fill": 0.1981,
  "fp_cx": 61.02,
  "fp_cy": 121.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_3": {
  "file": "man_at_arms_red_idle_d7_3.png",
  "fill": 0.1977,
  "fp_cx": 61.02,
  "fp_cy": 121.18,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_4": {
  "file": "man_at_arms_red_idle_d7_4.png",
  "fill": 0.1979,
  "fp_cx": 61.02,
  "fp_cy": 121.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_5": {
  "file": "man_at_arms_red_idle_d7_5.png",
  "fill": 0.1985,
  "fp_cx": 61.02,
  "fp_cy": 121.36,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0": {
  "clip": "walk",
  "dir": 0,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d0_0.png",
   "man_at_arms_red_walk_d0_1.png",
   "man_at_arms_red_walk_d0_2.png",
   "man_at_arms_red_walk_d0_3.png",
   "man_at_arms_red_walk_d0_4.png",
   "man_at_arms_red_walk_d0_5.png",
   "man_at_arms_red_walk_d0_6.png",
   "man_at_arms_red_walk_d0_7.png",
   "man_at_arms_red_walk_d0_8.png",
   "man_at_arms_red_walk_d0_9.png",
   "man_at_arms_red_walk_d0_10.png",
   "man_at_arms_red_walk_d0_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d0_0": {
  "file": "man_at_arms_red_walk_d0_0.png",
  "fill": 0.1622,
  "fp_cx": 67.94,
  "fp_cy": 124.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_1": {
  "file": "man_at_arms_red_walk_d0_1.png",
  "fill": 0.1599,
  "fp_cx": 65.12,
  "fp_cy": 123.2,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_10": {
  "file": "man_at_arms_red_walk_d0_10.png",
  "fill": 0.1572,
  "fp_cx": 71.26,
  "fp_cy": 126.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_11": {
  "file": "man_at_arms_red_walk_d0_11.png",
  "fill": 0.1638,
  "fp_cx": 71.66,
  "fp_cy": 126.46,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_2": {
  "file": "man_at_arms_red_walk_d0_2.png",
  "fill": 0.1574,
  "fp_cx": 64.82,
  "fp_cy": 123.16,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_3": {
  "file": "man_at_arms_red_walk_d0_3.png",
  "fill": 0.1601,
  "fp_cx": 68.7,
  "fp_cy": 125.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_4": {
  "file": "man_at_arms_red_walk_d0_4.png",
  "fill": 0.1609,
  "fp_cx": 70.88,
  "fp_cy": 126.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_5": {
  "file": "man_at_arms_red_walk_d0_5.png",
  "fill": 0.1582,
  "fp_cx": 71.04,
  "fp_cy": 126.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_6": {
  "file": "man_at_arms_red_walk_d0_6.png",
  "fill": 0.1537,
  "fp_cx": 67.22,
  "fp_cy": 124.84,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_7": {
  "file": "man_at_arms_red_walk_d0_7.png",
  "fill": 0.1568,
  "fp_cx": 64.5,
  "fp_cy": 123.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_8": {
  "file": "man_at_arms_red_walk_d0_8.png",
  "fill": 0.1618,
  "fp_cx": 64.48,
  "fp_cy": 123.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_9": {
  "file": "man_at_arms_red_walk_d0_9.png",
  "fill": 0.1599,
  "fp_cx": 68.76,
  "fp_cy": 125.3,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1": {
  "clip": "walk",
  "dir": 1,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d1_0.png",
   "man_at_arms_red_walk_d1_1.png",
   "man_at_arms_red_walk_d1_2.png",
   "man_at_arms_red_walk_d1_3.png",
   "man_at_arms_red_walk_d1_4.png",
   "man_at_arms_red_walk_d1_5.png",
   "man_at_arms_red_walk_d1_6.png",
   "man_at_arms_red_walk_d1_7.png",
   "man_at_arms_red_walk_d1_8.png",
   "man_at_arms_red_walk_d1_9.png",
   "man_at_arms_red_walk_d1_10.png",
   "man_at_arms_red_walk_d1_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d1_0": {
  "file": "man_at_arms_red_walk_d1_0.png",
  "fill": 0.1339,
  "fp_cx": 71.2,
  "fp_cy": 131.1,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_1": {
  "file": "man_at_arms_red_walk_d1_1.png",
  "fill": 0.1304,
  "fp_cx": 67.28,
  "fp_cy": 131.14,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_10": {
  "file": "man_at_arms_red_walk_d1_10.png",
  "fill": 0.1248,
  "fp_cx": 76.12,
  "fp_cy": 131.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_11": {
  "file": "man_at_arms_red_walk_d1_11.png",
  "fill": 0.1306,
  "fp_cx": 76.52,
  "fp_cy": 131.14,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_2": {
  "file": "man_at_arms_red_walk_d1_2.png",
  "fill": 0.1159,
  "fp_cx": 67.02,
  "fp_cy": 131.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_3": {
  "file": "man_at_arms_red_walk_d1_3.png",
  "fill": 0.1086,
  "fp_cx": 72.74,
  "fp_cy": 131.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_4": {
  "file": "man_at_arms_red_walk_d1_4.png",
  "fill": 0.1244,
  "fp_cx": 76.04,
  "fp_cy": 131.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_5": {
  "file": "man_at_arms_red_walk_d1_5.png",
  "fill": 0.1269,
  "fp_cx": 76.42,
  "fp_cy": 131.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_6": {
  "file": "man_at_arms_red_walk_d1_6.png",
  "fill": 0.1296,
  "fp_cx": 71.1,
  "fp_cy": 131.56,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_7": {
  "file": "man_at_arms_red_walk_d1_7.png",
  "fill": 0.125,
  "fp_cx": 67.2,
  "fp_cy": 131.52,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_8": {
  "file": "man_at_arms_red_walk_d1_8.png",
  "fill": 0.1157,
  "fp_cx": 67.0,
  "fp_cy": 131.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_9": {
  "file": "man_at_arms_red_walk_d1_9.png",
  "fill": 0.1073,
  "fp_cx": 72.82,
  "fp_cy": 131.32,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2": {
  "clip": "walk",
  "dir": 2,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d2_0.png",
   "man_at_arms_red_walk_d2_1.png",
   "man_at_arms_red_walk_d2_2.png",
   "man_at_arms_red_walk_d2_3.png",
   "man_at_arms_red_walk_d2_4.png",
   "man_at_arms_red_walk_d2_5.png",
   "man_at_arms_red_walk_d2_6.png",
   "man_at_arms_red_walk_d2_7.png",
   "man_at_arms_red_walk_d2_8.png",
   "man_at_arms_red_walk_d2_9.png",
   "man_at_arms_red_walk_d2_10.png",
   "man_at_arms_red_walk_d2_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d2_0": {
  "file": "man_at_arms_red_walk_d2_0.png",
  "fill": 0.1534,
  "fp_cx": 71.32,
  "fp_cy": 125.26,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_1": {
  "file": "man_at_arms_red_walk_d2_1.png",
  "fill": 0.1512,
  "fp_cx": 68.58,
  "fp_cy": 126.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_10": {
  "file": "man_at_arms_red_walk_d2_10.png",
  "fill": 0.1561,
  "fp_cx": 74.96,
  "fp_cy": 123.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_11": {
  "file": "man_at_arms_red_walk_d2_11.png",
  "fill": 0.1539,
  "fp_cx": 75.12,
  "fp_cy": 123.4,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_2": {
  "file": "man_at_arms_red_walk_d2_2.png",
  "fill": 0.1487,
  "fp_cx": 68.52,
  "fp_cy": 126.82,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_3": {
  "file": "man_at_arms_red_walk_d2_3.png",
  "fill": 0.1584,
  "fp_cx": 72.72,
  "fp_cy": 124.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_4": {
  "file": "man_at_arms_red_walk_d2_4.png",
  "fill": 0.1568,
  "fp_cx": 75.22,
  "fp_cy": 123.8,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_5": {
  "file": "man_at_arms_red_walk_d2_5.png",
  "fill": 0.1686,
  "fp_cx": 75.6,
  "fp_cy": 123.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_6": {
  "file": "man_at_arms_red_walk_d2_6.png",
  "fill": 0.1696,
  "fp_cx": 71.88,
  "fp_cy": 125.62,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_7": {
  "file": "man_at_arms_red_walk_d2_7.png",
  "fill": 0.1603,
  "fp_cx": 69.06,
  "fp_cy": 126.98,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_8": {
  "file": "man_at_arms_red_walk_d2_8.png",
  "fill": 0.152,
  "fp_cx": 68.82,
  "fp_cy": 127.0,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_9": {
  "file": "man_at_arms_red_walk_d2_9.png",
  "fill": 0.1539,
  "fp_cx": 72.78,
  "fp_cy": 124.86,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3": {
  "clip": "walk",
  "dir": 3,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d3_0.png",
   "man_at_arms_red_walk_d3_1.png",
   "man_at_arms_red_walk_d3_2.png",
   "man_at_arms_red_walk_d3_3.png",
   "man_at_arms_red_walk_d3_4.png",
   "man_at_arms_red_walk_d3_5.png",
   "man_at_arms_red_walk_d3_6.png",
   "man_at_arms_red_walk_d3_7.png",
   "man_at_arms_red_walk_d3_8.png",
   "man_at_arms_red_walk_d3_9.png",
   "man_at_arms_red_walk_d3_10.png",
   "man_at_arms_red_walk_d3_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d3_0": {
  "file": "man_at_arms_red_walk_d3_0.png",
  "fill": 0.1784,
  "fp_cx": 82.32,
  "fp_cy": 123.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_1": {
  "file": "man_at_arms_red_walk_d3_1.png",
  "fill": 0.1809,
  "fp_cx": 82.38,
  "fp_cy": 125.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_10": {
  "file": "man_at_arms_red_walk_d3_10.png",
  "fill": 0.1871,
  "fp_cx": 82.56,
  "fp_cy": 121.18,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_11": {
  "file": "man_at_arms_red_walk_d3_11.png",
  "fill": 0.1806,
  "fp_cx": 82.38,
  "fp_cy": 120.98,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_2": {
  "file": "man_at_arms_red_walk_d3_2.png",
  "fill": 0.1802,
  "fp_cx": 82.56,
  "fp_cy": 125.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_3": {
  "file": "man_at_arms_red_walk_d3_3.png",
  "fill": 0.1819,
  "fp_cx": 82.78,
  "fp_cy": 122.86,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_4": {
  "file": "man_at_arms_red_walk_d3_4.png",
  "fill": 0.1829,
  "fp_cx": 83.0,
  "fp_cy": 121.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_5": {
  "file": "man_at_arms_red_walk_d3_5.png",
  "fill": 0.1775,
  "fp_cx": 83.16,
  "fp_cy": 121.02,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_6": {
  "file": "man_at_arms_red_walk_d3_6.png",
  "fill": 0.1759,
  "fp_cx": 83.22,
  "fp_cy": 123.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_7": {
  "file": "man_at_arms_red_walk_d3_7.png",
  "fill": 0.1765,
  "fp_cx": 83.16,
  "fp_cy": 125.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_8": {
  "file": "man_at_arms_red_walk_d3_8.png",
  "fill": 0.1765,
  "fp_cx": 83.0,
  "fp_cy": 125.74,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_9": {
  "file": "man_at_arms_red_walk_d3_9.png",
  "fill": 0.1829,
  "fp_cx": 82.78,
  "fp_cy": 122.82,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4": {
  "clip": "walk",
  "dir": 4,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d4_0.png",
   "man_at_arms_red_walk_d4_1.png",
   "man_at_arms_red_walk_d4_2.png",
   "man_at_arms_red_walk_d4_3.png",
   "man_at_arms_red_walk_d4_4.png",
   "man_at_arms_red_walk_d4_5.png",
   "man_at_arms_red_walk_d4_6.png",
   "man_at_arms_red_walk_d4_7.png",
   "man_at_arms_red_walk_d4_8.png",
   "man_at_arms_red_walk_d4_9.png",
   "man_at_arms_red_walk_d4_10.png",
   "man_at_arms_red_walk_d4_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d4_0": {
  "file": "man_at_arms_red_walk_d4_0.png",
  "fill": 0.1485,
  "fp_cx": 76.06,
  "fp_cy": 123.6,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_1": {
  "file": "man_at_arms_red_walk_d4_1.png",
  "fill": 0.1422,
  "fp_cx": 78.88,
  "fp_cy": 124.96,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_10": {
  "file": "man_at_arms_red_walk_d4_10.png",
  "fill": 0.1458,
  "fp_cx": 72.74,
  "fp_cy": 121.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_11": {
  "file": "man_at_arms_red_walk_d4_11.png",
  "fill": 0.1522,
  "fp_cx": 72.34,
  "fp_cy": 121.68,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_2": {
  "file": "man_at_arms_red_walk_d4_2.png",
  "fill": 0.1352,
  "fp_cx": 79.18,
  "fp_cy": 125.0,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_3": {
  "file": "man_at_arms_red_walk_d4_3.png",
  "fill": 0.1402,
  "fp_cx": 75.3,
  "fp_cy": 122.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_4": {
  "file": "man_at_arms_red_walk_d4_4.png",
  "fill": 0.141,
  "fp_cx": 73.12,
  "fp_cy": 121.64,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_5": {
  "file": "man_at_arms_red_walk_d4_5.png",
  "fill": 0.1341,
  "fp_cx": 72.96,
  "fp_cy": 121.44,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_6": {
  "file": "man_at_arms_red_walk_d4_6.png",
  "fill": 0.1325,
  "fp_cx": 76.78,
  "fp_cy": 123.3,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_7": {
  "file": "man_at_arms_red_walk_d4_7.png",
  "fill": 0.1304,
  "fp_cx": 79.5,
  "fp_cy": 124.72,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_8": {
  "file": "man_at_arms_red_walk_d4_8.png",
  "fill": 0.1346,
  "fp_cx": 79.52,
  "fp_cy": 124.84,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_9": {
  "file": "man_at_arms_red_walk_d4_9.png",
  "fill": 0.1424,
  "fp_cx": 75.24,
  "fp_cy": 122.86,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5": {
  "clip": "walk",
  "dir": 5,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d5_0.png",
   "man_at_arms_red_walk_d5_1.png",
   "man_at_arms_red_walk_d5_2.png",
   "man_at_arms_red_walk_d5_3.png",
   "man_at_arms_red_walk_d5_4.png",
   "man_at_arms_red_walk_d5_5.png",
   "man_at_arms_red_walk_d5_6.png",
   "man_at_arms_red_walk_d5_7.png",
   "man_at_arms_red_walk_d5_8.png",
   "man_at_arms_red_walk_d5_9.png",
   "man_at_arms_red_walk_d5_10.png",
   "man_at_arms_red_walk_d5_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d5_0": {
  "file": "man_at_arms_red_walk_d5_0.png",
  "fill": 0.1481,
  "fp_cx": 72.8,
  "fp_cy": 129.0,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_1": {
  "file": "man_at_arms_red_walk_d5_1.png",
  "fill": 0.1408,
  "fp_cx": 76.72,
  "fp_cy": 128.96,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_10": {
  "file": "man_at_arms_red_walk_d5_10.png",
  "fill": 0.1343,
  "fp_cx": 67.88,
  "fp_cy": 128.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_11": {
  "file": "man_at_arms_red_walk_d5_11.png",
  "fill": 0.1456,
  "fp_cx": 67.48,
  "fp_cy": 128.96,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_2": {
  "file": "man_at_arms_red_walk_d5_2.png",
  "fill": 0.1169,
  "fp_cx": 76.98,
  "fp_cy": 128.88,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_3": {
  "file": "man_at_arms_red_walk_d5_3.png",
  "fill": 0.1071,
  "fp_cx": 71.26,
  "fp_cy": 128.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_4": {
  "file": "man_at_arms_red_walk_d5_4.png",
  "fill": 0.1356,
  "fp_cx": 67.96,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_5": {
  "file": "man_at_arms_red_walk_d5_5.png",
  "fill": 0.1427,
  "fp_cx": 67.58,
  "fp_cy": 128.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_6": {
  "file": "man_at_arms_red_walk_d5_6.png",
  "fill": 0.1437,
  "fp_cx": 72.9,
  "fp_cy": 128.54,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_7": {
  "file": "man_at_arms_red_walk_d5_7.png",
  "fill": 0.1385,
  "fp_cx": 76.8,
  "fp_cy": 128.58,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_8": {
  "file": "man_at_arms_red_walk_d5_8.png",
  "fill": 0.1219,
  "fp_cx": 77.0,
  "fp_cy": 128.66,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_9": {
  "file": "man_at_arms_red_walk_d5_9.png",
  "fill": 0.1115,
  "fp_cx": 71.18,
  "fp_cy": 128.76,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6": {
  "clip": "walk",
  "dir": 6,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d6_0.png",
   "man_at_arms_red_walk_d6_1.png",
   "man_at_arms_red_walk_d6_2.png",
   "man_at_arms_red_walk_d6_3.png",
   "man_at_arms_red_walk_d6_4.png",
   "man_at_arms_red_walk_d6_5.png",
   "man_at_arms_red_walk_d6_6.png",
   "man_at_arms_red_walk_d6_7.png",
   "man_at_arms_red_walk_d6_8.png",
   "man_at_arms_red_walk_d6_9.png",
   "man_at_arms_red_walk_d6_10.png",
   "man_at_arms_red_walk_d6_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d6_0": {
  "file": "man_at_arms_red_walk_d6_0.png",
  "fill": 0.1611,
  "fp_cx": 72.68,
  "fp_cy": 122.84,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_1": {
  "file": "man_at_arms_red_walk_d6_1.png",
  "fill": 0.1605,
  "fp_cx": 75.42,
  "fp_cy": 121.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_10": {
  "file": "man_at_arms_red_walk_d6_10.png",
  "fill": 0.1645,
  "fp_cx": 69.04,
  "fp_cy": 124.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_11": {
  "file": "man_at_arms_red_walk_d6_11.png",
  "fill": 0.1622,
  "fp_cx": 68.88,
  "fp_cy": 124.7,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_2": {
  "file": "man_at_arms_red_walk_d6_2.png",
  "fill": 0.1651,
  "fp_cx": 75.48,
  "fp_cy": 121.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_3": {
  "file": "man_at_arms_red_walk_d6_3.png",
  "fill": 0.1775,
  "fp_cx": 71.28,
  "fp_cy": 123.22,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_4": {
  "file": "man_at_arms_red_walk_d6_4.png",
  "fill": 0.1779,
  "fp_cx": 68.78,
  "fp_cy": 124.3,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_5": {
  "file": "man_at_arms_red_walk_d6_5.png",
  "fill": 0.1773,
  "fp_cx": 68.4,
  "fp_cy": 124.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_6": {
  "file": "man_at_arms_red_walk_d6_6.png",
  "fill": 0.1755,
  "fp_cx": 72.12,
  "fp_cy": 122.48,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_7": {
  "file": "man_at_arms_red_walk_d6_7.png",
  "fill": 0.1748,
  "fp_cx": 74.94,
  "fp_cy": 121.12,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_8": {
  "file": "man_at_arms_red_walk_d6_8.png",
  "fill": 0.1755,
  "fp_cx": 75.18,
  "fp_cy": 121.1,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_9": {
  "file": "man_at_arms_red_walk_d6_9.png",
  "fill": 0.1752,
  "fp_cx": 71.22,
  "fp_cy": 123.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7": {
  "clip": "walk",
  "dir": 7,
  "duration": 1.1667,
  "files": [
   "man_at_arms_red_walk_d7_0.png",
   "man_at_arms_red_walk_d7_1.png",
   "man_at_arms_red_walk_d7_2.png",
   "man_at_arms_red_walk_d7_3.png",
   "man_at_arms_red_walk_d7_4.png",
   "man_at_arms_red_walk_d7_5.png",
   "man_at_arms_red_walk_d7_6.png",
   "man_at_arms_red_walk_d7_7.png",
   "man_at_arms_red_walk_d7_8.png",
   "man_at_arms_red_walk_d7_9.png",
   "man_at_arms_red_walk_d7_10.png",
   "man_at_arms_red_walk_d7_11.png"
  ],
  "fps": 10.285,
  "frames": 12,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d7_0": {
  "file": "man_at_arms_red_walk_d7_0.png",
  "fill": 0.1896,
  "fp_cx": 61.68,
  "fp_cy": 124.48,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_1": {
  "file": "man_at_arms_red_walk_d7_1.png",
  "fill": 0.189,
  "fp_cx": 61.62,
  "fp_cy": 122.5,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_10": {
  "file": "man_at_arms_red_walk_d7_10.png",
  "fill": 0.1975,
  "fp_cx": 61.44,
  "fp_cy": 126.94,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_11": {
  "file": "man_at_arms_red_walk_d7_11.png",
  "fill": 0.1925,
  "fp_cx": 61.62,
  "fp_cy": 127.14,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_2": {
  "file": "man_at_arms_red_walk_d7_2.png",
  "fill": 0.1917,
  "fp_cx": 61.44,
  "fp_cy": 122.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_3": {
  "file": "man_at_arms_red_walk_d7_3.png",
  "fill": 0.1971,
  "fp_cx": 61.22,
  "fp_cy": 125.24,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_4": {
  "file": "man_at_arms_red_walk_d7_4.png",
  "fill": 0.202,
  "fp_cx": 61.0,
  "fp_cy": 126.9,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_5": {
  "file": "man_at_arms_red_walk_d7_5.png",
  "fill": 0.1937,
  "fp_cx": 60.84,
  "fp_cy": 127.08,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_6": {
  "file": "man_at_arms_red_walk_d7_6.png",
  "fill": 0.1894,
  "fp_cx": 60.78,
  "fp_cy": 124.42,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_7": {
  "file": "man_at_arms_red_walk_d7_7.png",
  "fill": 0.1927,
  "fp_cx": 60.84,
  "fp_cy": 122.46,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_8": {
  "file": "man_at_arms_red_walk_d7_8.png",
  "fill": 0.1964,
  "fp_cx": 61.0,
  "fp_cy": 122.38,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_9": {
  "file": "man_at_arms_red_walk_d7_9.png",
  "fill": 0.1968,
  "fp_cx": 61.22,
  "fp_cy": 125.28,
  "fp_w": 47.0,
  "h": 144,
  "w": 144
 }
});
