/* Generated by art/pipeline/install_unit_sprites.py from art/out/man_at_arms/sprites@2x */
window.POCKET_EMPIRES_SPRITES = Object.assign(window.POCKET_EMPIRES_SPRITES || {}, {
 "man_at_arms": {
  "clips": [
   "idle",
   "walk"
  ],
  "dirs": 8,
  "group": "directional_unit",
  "key_format": "man_at_arms_<team>_<clip>_d<dir>[_<frame>]",
  "note": "direction k = camera yaw 45 + 45*k deg (counter-clockwise from above); d0 matches the single facing the existing 0 A.D. units were baked at",
  "pitch": 30.0,
  "teams": [
   "blue",
   "red"
  ],
  "yaw0": 45.0
 },
 "man_at_arms_blue_idle_d0": {
  "clip": "idle",
  "dir": 0,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d0_0.png",
   "man_at_arms_blue_idle_d0_1.png",
   "man_at_arms_blue_idle_d0_2.png",
   "man_at_arms_blue_idle_d0_3.png",
   "man_at_arms_blue_idle_d0_4.png",
   "man_at_arms_blue_idle_d0_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d0_0": {
  "file": "man_at_arms_blue_idle_d0_0.png",
  "fill": 0.2479,
  "fp_cx": 65.14,
  "fp_cy": 129.9,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_1": {
  "file": "man_at_arms_blue_idle_d0_1.png",
  "fill": 0.2465,
  "fp_cx": 64.96,
  "fp_cy": 129.82,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_2": {
  "file": "man_at_arms_blue_idle_d0_2.png",
  "fill": 0.244,
  "fp_cx": 64.86,
  "fp_cy": 129.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_3": {
  "file": "man_at_arms_blue_idle_d0_3.png",
  "fill": 0.2444,
  "fp_cx": 64.82,
  "fp_cy": 129.76,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_4": {
  "file": "man_at_arms_blue_idle_d0_4.png",
  "fill": 0.2438,
  "fp_cx": 64.86,
  "fp_cy": 129.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d0_5": {
  "file": "man_at_arms_blue_idle_d0_5.png",
  "fill": 0.2465,
  "fp_cx": 64.96,
  "fp_cy": 129.82,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1": {
  "clip": "idle",
  "dir": 1,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d1_0.png",
   "man_at_arms_blue_idle_d1_1.png",
   "man_at_arms_blue_idle_d1_2.png",
   "man_at_arms_blue_idle_d1_3.png",
   "man_at_arms_blue_idle_d1_4.png",
   "man_at_arms_blue_idle_d1_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d1_0": {
  "file": "man_at_arms_blue_idle_d1_0.png",
  "fill": 0.179,
  "fp_cx": 63.58,
  "fp_cy": 133.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_1": {
  "file": "man_at_arms_blue_idle_d1_1.png",
  "fill": 0.18,
  "fp_cx": 63.36,
  "fp_cy": 133.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_2": {
  "file": "man_at_arms_blue_idle_d1_2.png",
  "fill": 0.1794,
  "fp_cx": 63.22,
  "fp_cy": 133.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_3": {
  "file": "man_at_arms_blue_idle_d1_3.png",
  "fill": 0.1804,
  "fp_cx": 63.16,
  "fp_cy": 133.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_4": {
  "file": "man_at_arms_blue_idle_d1_4.png",
  "fill": 0.1794,
  "fp_cx": 63.22,
  "fp_cy": 133.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d1_5": {
  "file": "man_at_arms_blue_idle_d1_5.png",
  "fill": 0.18,
  "fp_cx": 63.36,
  "fp_cy": 133.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2": {
  "clip": "idle",
  "dir": 2,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d2_0.png",
   "man_at_arms_blue_idle_d2_1.png",
   "man_at_arms_blue_idle_d2_2.png",
   "man_at_arms_blue_idle_d2_3.png",
   "man_at_arms_blue_idle_d2_4.png",
   "man_at_arms_blue_idle_d2_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d2_0": {
  "file": "man_at_arms_blue_idle_d2_0.png",
  "fill": 0.2166,
  "fp_cx": 70.6,
  "fp_cy": 130.38,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_1": {
  "file": "man_at_arms_blue_idle_d2_1.png",
  "fill": 0.2166,
  "fp_cx": 70.44,
  "fp_cy": 130.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_2": {
  "file": "man_at_arms_blue_idle_d2_2.png",
  "fill": 0.216,
  "fp_cx": 70.36,
  "fp_cy": 130.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_3": {
  "file": "man_at_arms_blue_idle_d2_3.png",
  "fill": 0.2162,
  "fp_cx": 70.32,
  "fp_cy": 130.54,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_4": {
  "file": "man_at_arms_blue_idle_d2_4.png",
  "fill": 0.216,
  "fp_cx": 70.36,
  "fp_cy": 130.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d2_5": {
  "file": "man_at_arms_blue_idle_d2_5.png",
  "fill": 0.2164,
  "fp_cx": 70.44,
  "fp_cy": 130.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3": {
  "clip": "idle",
  "dir": 3,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d3_0.png",
   "man_at_arms_blue_idle_d3_1.png",
   "man_at_arms_blue_idle_d3_2.png",
   "man_at_arms_blue_idle_d3_3.png",
   "man_at_arms_blue_idle_d3_4.png",
   "man_at_arms_blue_idle_d3_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d3_0": {
  "file": "man_at_arms_blue_idle_d3_0.png",
  "fill": 0.2429,
  "fp_cx": 83.6,
  "fp_cy": 126.62,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_1": {
  "file": "man_at_arms_blue_idle_d3_1.png",
  "fill": 0.2431,
  "fp_cx": 83.62,
  "fp_cy": 126.74,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_2": {
  "file": "man_at_arms_blue_idle_d3_2.png",
  "fill": 0.2432,
  "fp_cx": 83.64,
  "fp_cy": 126.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_3": {
  "file": "man_at_arms_blue_idle_d3_3.png",
  "fill": 0.2432,
  "fp_cx": 83.64,
  "fp_cy": 126.84,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_4": {
  "file": "man_at_arms_blue_idle_d3_4.png",
  "fill": 0.2434,
  "fp_cx": 83.64,
  "fp_cy": 126.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d3_5": {
  "file": "man_at_arms_blue_idle_d3_5.png",
  "fill": 0.2431,
  "fp_cx": 83.62,
  "fp_cy": 126.74,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4": {
  "clip": "idle",
  "dir": 4,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d4_0.png",
   "man_at_arms_blue_idle_d4_1.png",
   "man_at_arms_blue_idle_d4_2.png",
   "man_at_arms_blue_idle_d4_3.png",
   "man_at_arms_blue_idle_d4_4.png",
   "man_at_arms_blue_idle_d4_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d4_0": {
  "file": "man_at_arms_blue_idle_d4_0.png",
  "fill": 0.1941,
  "fp_cx": 78.86,
  "fp_cy": 128.2,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_1": {
  "file": "man_at_arms_blue_idle_d4_1.png",
  "fill": 0.195,
  "fp_cx": 79.04,
  "fp_cy": 128.26,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_2": {
  "file": "man_at_arms_blue_idle_d4_2.png",
  "fill": 0.195,
  "fp_cx": 79.14,
  "fp_cy": 128.32,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_3": {
  "file": "man_at_arms_blue_idle_d4_3.png",
  "fill": 0.1958,
  "fp_cx": 79.18,
  "fp_cy": 128.32,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_4": {
  "file": "man_at_arms_blue_idle_d4_4.png",
  "fill": 0.195,
  "fp_cx": 79.14,
  "fp_cy": 128.32,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d4_5": {
  "file": "man_at_arms_blue_idle_d4_5.png",
  "fill": 0.1952,
  "fp_cx": 79.04,
  "fp_cy": 128.26,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5": {
  "clip": "idle",
  "dir": 5,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d5_0.png",
   "man_at_arms_blue_idle_d5_1.png",
   "man_at_arms_blue_idle_d5_2.png",
   "man_at_arms_blue_idle_d5_3.png",
   "man_at_arms_blue_idle_d5_4.png",
   "man_at_arms_blue_idle_d5_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d5_0": {
  "file": "man_at_arms_blue_idle_d5_0.png",
  "fill": 0.1632,
  "fp_cx": 80.42,
  "fp_cy": 129.12,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_1": {
  "file": "man_at_arms_blue_idle_d5_1.png",
  "fill": 0.1644,
  "fp_cx": 80.64,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_2": {
  "file": "man_at_arms_blue_idle_d5_2.png",
  "fill": 0.1647,
  "fp_cx": 80.78,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_3": {
  "file": "man_at_arms_blue_idle_d5_3.png",
  "fill": 0.1645,
  "fp_cx": 80.84,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_4": {
  "file": "man_at_arms_blue_idle_d5_4.png",
  "fill": 0.1647,
  "fp_cx": 80.78,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d5_5": {
  "file": "man_at_arms_blue_idle_d5_5.png",
  "fill": 0.1644,
  "fp_cx": 80.64,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6": {
  "clip": "idle",
  "dir": 6,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d6_0.png",
   "man_at_arms_blue_idle_d6_1.png",
   "man_at_arms_blue_idle_d6_2.png",
   "man_at_arms_blue_idle_d6_3.png",
   "man_at_arms_blue_idle_d6_4.png",
   "man_at_arms_blue_idle_d6_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d6_0": {
  "file": "man_at_arms_blue_idle_d6_0.png",
  "fill": 0.2436,
  "fp_cx": 73.4,
  "fp_cy": 127.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_1": {
  "file": "man_at_arms_blue_idle_d6_1.png",
  "fill": 0.2415,
  "fp_cx": 73.56,
  "fp_cy": 127.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_2": {
  "file": "man_at_arms_blue_idle_d6_2.png",
  "fill": 0.2402,
  "fp_cx": 73.64,
  "fp_cy": 127.36,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_3": {
  "file": "man_at_arms_blue_idle_d6_3.png",
  "fill": 0.2394,
  "fp_cx": 73.68,
  "fp_cy": 127.34,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_4": {
  "file": "man_at_arms_blue_idle_d6_4.png",
  "fill": 0.2402,
  "fp_cx": 73.64,
  "fp_cy": 127.36,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d6_5": {
  "file": "man_at_arms_blue_idle_d6_5.png",
  "fill": 0.2413,
  "fp_cx": 73.56,
  "fp_cy": 127.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7": {
  "clip": "idle",
  "dir": 7,
  "duration": 2.5,
  "files": [
   "man_at_arms_blue_idle_d7_0.png",
   "man_at_arms_blue_idle_d7_1.png",
   "man_at_arms_blue_idle_d7_2.png",
   "man_at_arms_blue_idle_d7_3.png",
   "man_at_arms_blue_idle_d7_4.png",
   "man_at_arms_blue_idle_d7_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_idle_d7_0": {
  "file": "man_at_arms_blue_idle_d7_0.png",
  "fill": 0.2693,
  "fp_cx": 60.4,
  "fp_cy": 127.88,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_1": {
  "file": "man_at_arms_blue_idle_d7_1.png",
  "fill": 0.2687,
  "fp_cx": 60.38,
  "fp_cy": 127.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_2": {
  "file": "man_at_arms_blue_idle_d7_2.png",
  "fill": 0.2679,
  "fp_cx": 60.36,
  "fp_cy": 127.7,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_3": {
  "file": "man_at_arms_blue_idle_d7_3.png",
  "fill": 0.2676,
  "fp_cx": 60.36,
  "fp_cy": 127.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_4": {
  "file": "man_at_arms_blue_idle_d7_4.png",
  "fill": 0.2681,
  "fp_cx": 60.36,
  "fp_cy": 127.7,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_idle_d7_5": {
  "file": "man_at_arms_blue_idle_d7_5.png",
  "fill": 0.2687,
  "fp_cx": 60.38,
  "fp_cy": 127.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0": {
  "clip": "walk",
  "dir": 0,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d0_0.png",
   "man_at_arms_blue_walk_d0_1.png",
   "man_at_arms_blue_walk_d0_2.png",
   "man_at_arms_blue_walk_d0_3.png",
   "man_at_arms_blue_walk_d0_4.png",
   "man_at_arms_blue_walk_d0_5.png",
   "man_at_arms_blue_walk_d0_6.png",
   "man_at_arms_blue_walk_d0_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d0_0": {
  "file": "man_at_arms_blue_walk_d0_0.png",
  "fill": 0.2571,
  "fp_cx": 65.02,
  "fp_cy": 129.38,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_1": {
  "file": "man_at_arms_blue_walk_d0_1.png",
  "fill": 0.2649,
  "fp_cx": 68.3,
  "fp_cy": 131.22,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_2": {
  "file": "man_at_arms_blue_walk_d0_2.png",
  "fill": 0.2456,
  "fp_cx": 69.48,
  "fp_cy": 130.6,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_3": {
  "file": "man_at_arms_blue_walk_d0_3.png",
  "fill": 0.2355,
  "fp_cx": 64.32,
  "fp_cy": 126.06,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_4": {
  "file": "man_at_arms_blue_walk_d0_4.png",
  "fill": 0.2419,
  "fp_cx": 68.34,
  "fp_cy": 126.74,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_5": {
  "file": "man_at_arms_blue_walk_d0_5.png",
  "fill": 0.255,
  "fp_cx": 72.34,
  "fp_cy": 128.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_6": {
  "file": "man_at_arms_blue_walk_d0_6.png",
  "fill": 0.2579,
  "fp_cx": 70.52,
  "fp_cy": 128.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d0_7": {
  "file": "man_at_arms_blue_walk_d0_7.png",
  "fill": 0.2623,
  "fp_cx": 64.96,
  "fp_cy": 126.92,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1": {
  "clip": "walk",
  "dir": 1,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d1_0.png",
   "man_at_arms_blue_walk_d1_1.png",
   "man_at_arms_blue_walk_d1_2.png",
   "man_at_arms_blue_walk_d1_3.png",
   "man_at_arms_blue_walk_d1_4.png",
   "man_at_arms_blue_walk_d1_5.png",
   "man_at_arms_blue_walk_d1_6.png",
   "man_at_arms_blue_walk_d1_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d1_0": {
  "file": "man_at_arms_blue_walk_d1_0.png",
  "fill": 0.1954,
  "fp_cx": 62.78,
  "fp_cy": 133.16,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_1": {
  "file": "man_at_arms_blue_walk_d1_1.png",
  "fill": 0.1933,
  "fp_cx": 67.66,
  "fp_cy": 133.3,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_2": {
  "file": "man_at_arms_blue_walk_d1_2.png",
  "fill": 0.2006,
  "fp_cx": 67.64,
  "fp_cy": 132.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_3": {
  "file": "man_at_arms_blue_walk_d1_3.png",
  "fill": 0.1985,
  "fp_cx": 57.58,
  "fp_cy": 131.06,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_4": {
  "file": "man_at_arms_blue_walk_d1_4.png",
  "fill": 0.1865,
  "fp_cx": 61.38,
  "fp_cy": 130.12,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_5": {
  "file": "man_at_arms_blue_walk_d1_5.png",
  "fill": 0.2006,
  "fp_cx": 66.64,
  "fp_cy": 129.92,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_6": {
  "file": "man_at_arms_blue_walk_d1_6.png",
  "fill": 0.2149,
  "fp_cx": 65.42,
  "fp_cy": 130.6,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d1_7": {
  "file": "man_at_arms_blue_walk_d1_7.png",
  "fill": 0.212,
  "fp_cx": 59.24,
  "fp_cy": 131.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2": {
  "clip": "walk",
  "dir": 2,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d2_0.png",
   "man_at_arms_blue_walk_d2_1.png",
   "man_at_arms_blue_walk_d2_2.png",
   "man_at_arms_blue_walk_d2_3.png",
   "man_at_arms_blue_walk_d2_4.png",
   "man_at_arms_blue_walk_d2_5.png",
   "man_at_arms_blue_walk_d2_6.png",
   "man_at_arms_blue_walk_d2_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d2_0": {
  "file": "man_at_arms_blue_walk_d2_0.png",
  "fill": 0.1971,
  "fp_cx": 69.56,
  "fp_cy": 130.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_1": {
  "file": "man_at_arms_blue_walk_d2_1.png",
  "fill": 0.1943,
  "fp_cx": 73.22,
  "fp_cy": 128.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_2": {
  "file": "man_at_arms_blue_walk_d2_2.png",
  "fill": 0.2133,
  "fp_cx": 72.0,
  "fp_cy": 128.2,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_3": {
  "file": "man_at_arms_blue_walk_d2_3.png",
  "fill": 0.2097,
  "fp_cx": 62.94,
  "fp_cy": 130.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_4": {
  "file": "man_at_arms_blue_walk_d2_4.png",
  "fill": 0.202,
  "fp_cx": 64.28,
  "fp_cy": 128.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_5": {
  "file": "man_at_arms_blue_walk_d2_5.png",
  "fill": 0.2002,
  "fp_cx": 67.72,
  "fp_cy": 126.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_6": {
  "file": "man_at_arms_blue_walk_d2_6.png",
  "fill": 0.1981,
  "fp_cx": 67.82,
  "fp_cy": 127.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d2_7": {
  "file": "man_at_arms_blue_walk_d2_7.png",
  "fill": 0.1979,
  "fp_cx": 64.64,
  "fp_cy": 130.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3": {
  "clip": "walk",
  "dir": 3,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d3_0.png",
   "man_at_arms_blue_walk_d3_1.png",
   "man_at_arms_blue_walk_d3_2.png",
   "man_at_arms_blue_walk_d3_3.png",
   "man_at_arms_blue_walk_d3_4.png",
   "man_at_arms_blue_walk_d3_5.png",
   "man_at_arms_blue_walk_d3_6.png",
   "man_at_arms_blue_walk_d3_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d3_0": {
  "file": "man_at_arms_blue_walk_d3_0.png",
  "fill": 0.2299,
  "fp_cx": 82.96,
  "fp_cy": 127.02,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_1": {
  "file": "man_at_arms_blue_walk_d3_1.png",
  "fill": 0.2292,
  "fp_cx": 83.24,
  "fp_cy": 124.58,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_2": {
  "file": "man_at_arms_blue_walk_d3_2.png",
  "fill": 0.2265,
  "fp_cx": 81.54,
  "fp_cy": 124.6,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_3": {
  "file": "man_at_arms_blue_walk_d3_3.png",
  "fill": 0.2251,
  "fp_cx": 78.78,
  "fp_cy": 129.62,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_4": {
  "file": "man_at_arms_blue_walk_d3_4.png",
  "fill": 0.2297,
  "fp_cx": 76.88,
  "fp_cy": 127.72,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_5": {
  "file": "man_at_arms_blue_walk_d3_5.png",
  "fill": 0.2257,
  "fp_cx": 76.48,
  "fp_cy": 125.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_6": {
  "file": "man_at_arms_blue_walk_d3_6.png",
  "fill": 0.2189,
  "fp_cx": 77.84,
  "fp_cy": 125.7,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d3_7": {
  "file": "man_at_arms_blue_walk_d3_7.png",
  "fill": 0.2276,
  "fp_cx": 79.52,
  "fp_cy": 128.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4": {
  "clip": "walk",
  "dir": 4,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d4_0.png",
   "man_at_arms_blue_walk_d4_1.png",
   "man_at_arms_blue_walk_d4_2.png",
   "man_at_arms_blue_walk_d4_3.png",
   "man_at_arms_blue_walk_d4_4.png",
   "man_at_arms_blue_walk_d4_5.png",
   "man_at_arms_blue_walk_d4_6.png",
   "man_at_arms_blue_walk_d4_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d4_0": {
  "file": "man_at_arms_blue_walk_d4_0.png",
  "fill": 0.1944,
  "fp_cx": 78.98,
  "fp_cy": 128.72,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_1": {
  "file": "man_at_arms_blue_walk_d4_1.png",
  "fill": 0.1956,
  "fp_cx": 75.7,
  "fp_cy": 126.88,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_2": {
  "file": "man_at_arms_blue_walk_d4_2.png",
  "fill": 0.1879,
  "fp_cx": 74.52,
  "fp_cy": 127.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_3": {
  "file": "man_at_arms_blue_walk_d4_3.png",
  "fill": 0.1881,
  "fp_cx": 79.68,
  "fp_cy": 132.02,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_4": {
  "file": "man_at_arms_blue_walk_d4_4.png",
  "fill": 0.1883,
  "fp_cx": 75.66,
  "fp_cy": 131.36,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_5": {
  "file": "man_at_arms_blue_walk_d4_5.png",
  "fill": 0.1873,
  "fp_cx": 71.66,
  "fp_cy": 129.62,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_6": {
  "file": "man_at_arms_blue_walk_d4_6.png",
  "fill": 0.2066,
  "fp_cx": 73.48,
  "fp_cy": 129.58,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d4_7": {
  "file": "man_at_arms_blue_walk_d4_7.png",
  "fill": 0.2135,
  "fp_cx": 79.04,
  "fp_cy": 131.18,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5": {
  "clip": "walk",
  "dir": 5,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d5_0.png",
   "man_at_arms_blue_walk_d5_1.png",
   "man_at_arms_blue_walk_d5_2.png",
   "man_at_arms_blue_walk_d5_3.png",
   "man_at_arms_blue_walk_d5_4.png",
   "man_at_arms_blue_walk_d5_5.png",
   "man_at_arms_blue_walk_d5_6.png",
   "man_at_arms_blue_walk_d5_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d5_0": {
  "file": "man_at_arms_blue_walk_d5_0.png",
  "fill": 0.1647,
  "fp_cx": 81.22,
  "fp_cy": 129.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_1": {
  "file": "man_at_arms_blue_walk_d5_1.png",
  "fill": 0.174,
  "fp_cx": 76.34,
  "fp_cy": 129.3,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_2": {
  "file": "man_at_arms_blue_walk_d5_2.png",
  "fill": 0.1804,
  "fp_cx": 76.36,
  "fp_cy": 130.14,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_3": {
  "file": "man_at_arms_blue_walk_d5_3.png",
  "fill": 0.1775,
  "fp_cx": 86.42,
  "fp_cy": 131.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_4": {
  "file": "man_at_arms_blue_walk_d5_4.png",
  "fill": 0.1601,
  "fp_cx": 82.62,
  "fp_cy": 132.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_5": {
  "file": "man_at_arms_blue_walk_d5_5.png",
  "fill": 0.1599,
  "fp_cx": 77.36,
  "fp_cy": 132.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_6": {
  "file": "man_at_arms_blue_walk_d5_6.png",
  "fill": 0.1807,
  "fp_cx": 78.58,
  "fp_cy": 132.0,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d5_7": {
  "file": "man_at_arms_blue_walk_d5_7.png",
  "fill": 0.1856,
  "fp_cx": 84.76,
  "fp_cy": 131.16,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6": {
  "clip": "walk",
  "dir": 6,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d6_0.png",
   "man_at_arms_blue_walk_d6_1.png",
   "man_at_arms_blue_walk_d6_2.png",
   "man_at_arms_blue_walk_d6_3.png",
   "man_at_arms_blue_walk_d6_4.png",
   "man_at_arms_blue_walk_d6_5.png",
   "man_at_arms_blue_walk_d6_6.png",
   "man_at_arms_blue_walk_d6_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d6_0": {
  "file": "man_at_arms_blue_walk_d6_0.png",
  "fill": 0.2294,
  "fp_cx": 74.44,
  "fp_cy": 127.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_1": {
  "file": "man_at_arms_blue_walk_d6_1.png",
  "fill": 0.2431,
  "fp_cx": 70.78,
  "fp_cy": 129.08,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_2": {
  "file": "man_at_arms_blue_walk_d6_2.png",
  "fill": 0.2514,
  "fp_cx": 72.0,
  "fp_cy": 129.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_3": {
  "file": "man_at_arms_blue_walk_d6_3.png",
  "fill": 0.2346,
  "fp_cx": 81.06,
  "fp_cy": 127.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_4": {
  "file": "man_at_arms_blue_walk_d6_4.png",
  "fill": 0.2386,
  "fp_cx": 79.72,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_5": {
  "file": "man_at_arms_blue_walk_d6_5.png",
  "fill": 0.233,
  "fp_cx": 76.28,
  "fp_cy": 131.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_6": {
  "file": "man_at_arms_blue_walk_d6_6.png",
  "fill": 0.213,
  "fp_cx": 76.18,
  "fp_cy": 130.2,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d6_7": {
  "file": "man_at_arms_blue_walk_d6_7.png",
  "fill": 0.2222,
  "fp_cx": 79.36,
  "fp_cy": 127.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7": {
  "clip": "walk",
  "dir": 7,
  "duration": 1.6667,
  "files": [
   "man_at_arms_blue_walk_d7_0.png",
   "man_at_arms_blue_walk_d7_1.png",
   "man_at_arms_blue_walk_d7_2.png",
   "man_at_arms_blue_walk_d7_3.png",
   "man_at_arms_blue_walk_d7_4.png",
   "man_at_arms_blue_walk_d7_5.png",
   "man_at_arms_blue_walk_d7_6.png",
   "man_at_arms_blue_walk_d7_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "blue"
 },
 "man_at_arms_blue_walk_d7_0": {
  "file": "man_at_arms_blue_walk_d7_0.png",
  "fill": 0.2589,
  "fp_cx": 61.04,
  "fp_cy": 127.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_1": {
  "file": "man_at_arms_blue_walk_d7_1.png",
  "fill": 0.2683,
  "fp_cx": 60.76,
  "fp_cy": 129.94,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_2": {
  "file": "man_at_arms_blue_walk_d7_2.png",
  "fill": 0.2629,
  "fp_cx": 62.46,
  "fp_cy": 129.92,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_3": {
  "file": "man_at_arms_blue_walk_d7_3.png",
  "fill": 0.2537,
  "fp_cx": 65.22,
  "fp_cy": 124.88,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_4": {
  "file": "man_at_arms_blue_walk_d7_4.png",
  "fill": 0.2558,
  "fp_cx": 67.12,
  "fp_cy": 126.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_5": {
  "file": "man_at_arms_blue_walk_d7_5.png",
  "fill": 0.2604,
  "fp_cx": 67.52,
  "fp_cy": 129.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_6": {
  "file": "man_at_arms_blue_walk_d7_6.png",
  "fill": 0.2612,
  "fp_cx": 66.16,
  "fp_cy": 128.82,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_blue_walk_d7_7": {
  "file": "man_at_arms_blue_walk_d7_7.png",
  "fill": 0.2589,
  "fp_cx": 64.48,
  "fp_cy": 125.72,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0": {
  "clip": "idle",
  "dir": 0,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d0_0.png",
   "man_at_arms_red_idle_d0_1.png",
   "man_at_arms_red_idle_d0_2.png",
   "man_at_arms_red_idle_d0_3.png",
   "man_at_arms_red_idle_d0_4.png",
   "man_at_arms_red_idle_d0_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d0_0": {
  "file": "man_at_arms_red_idle_d0_0.png",
  "fill": 0.2483,
  "fp_cx": 65.14,
  "fp_cy": 129.9,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_1": {
  "file": "man_at_arms_red_idle_d0_1.png",
  "fill": 0.2463,
  "fp_cx": 64.96,
  "fp_cy": 129.82,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_2": {
  "file": "man_at_arms_red_idle_d0_2.png",
  "fill": 0.2442,
  "fp_cx": 64.86,
  "fp_cy": 129.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_3": {
  "file": "man_at_arms_red_idle_d0_3.png",
  "fill": 0.2446,
  "fp_cx": 64.82,
  "fp_cy": 129.76,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_4": {
  "file": "man_at_arms_red_idle_d0_4.png",
  "fill": 0.244,
  "fp_cx": 64.86,
  "fp_cy": 129.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d0_5": {
  "file": "man_at_arms_red_idle_d0_5.png",
  "fill": 0.2463,
  "fp_cx": 64.96,
  "fp_cy": 129.82,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1": {
  "clip": "idle",
  "dir": 1,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d1_0.png",
   "man_at_arms_red_idle_d1_1.png",
   "man_at_arms_red_idle_d1_2.png",
   "man_at_arms_red_idle_d1_3.png",
   "man_at_arms_red_idle_d1_4.png",
   "man_at_arms_red_idle_d1_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d1_0": {
  "file": "man_at_arms_red_idle_d1_0.png",
  "fill": 0.179,
  "fp_cx": 63.58,
  "fp_cy": 133.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_1": {
  "file": "man_at_arms_red_idle_d1_1.png",
  "fill": 0.18,
  "fp_cx": 63.36,
  "fp_cy": 133.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_2": {
  "file": "man_at_arms_red_idle_d1_2.png",
  "fill": 0.1794,
  "fp_cx": 63.22,
  "fp_cy": 133.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_3": {
  "file": "man_at_arms_red_idle_d1_3.png",
  "fill": 0.1802,
  "fp_cx": 63.16,
  "fp_cy": 133.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_4": {
  "file": "man_at_arms_red_idle_d1_4.png",
  "fill": 0.1794,
  "fp_cx": 63.22,
  "fp_cy": 133.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d1_5": {
  "file": "man_at_arms_red_idle_d1_5.png",
  "fill": 0.18,
  "fp_cx": 63.36,
  "fp_cy": 133.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2": {
  "clip": "idle",
  "dir": 2,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d2_0.png",
   "man_at_arms_red_idle_d2_1.png",
   "man_at_arms_red_idle_d2_2.png",
   "man_at_arms_red_idle_d2_3.png",
   "man_at_arms_red_idle_d2_4.png",
   "man_at_arms_red_idle_d2_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d2_0": {
  "file": "man_at_arms_red_idle_d2_0.png",
  "fill": 0.2168,
  "fp_cx": 70.6,
  "fp_cy": 130.38,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_1": {
  "file": "man_at_arms_red_idle_d2_1.png",
  "fill": 0.2166,
  "fp_cx": 70.44,
  "fp_cy": 130.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_2": {
  "file": "man_at_arms_red_idle_d2_2.png",
  "fill": 0.216,
  "fp_cx": 70.36,
  "fp_cy": 130.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_3": {
  "file": "man_at_arms_red_idle_d2_3.png",
  "fill": 0.2162,
  "fp_cx": 70.32,
  "fp_cy": 130.54,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_4": {
  "file": "man_at_arms_red_idle_d2_4.png",
  "fill": 0.216,
  "fp_cx": 70.36,
  "fp_cy": 130.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d2_5": {
  "file": "man_at_arms_red_idle_d2_5.png",
  "fill": 0.2164,
  "fp_cx": 70.44,
  "fp_cy": 130.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3": {
  "clip": "idle",
  "dir": 3,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d3_0.png",
   "man_at_arms_red_idle_d3_1.png",
   "man_at_arms_red_idle_d3_2.png",
   "man_at_arms_red_idle_d3_3.png",
   "man_at_arms_red_idle_d3_4.png",
   "man_at_arms_red_idle_d3_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d3_0": {
  "file": "man_at_arms_red_idle_d3_0.png",
  "fill": 0.2429,
  "fp_cx": 83.6,
  "fp_cy": 126.62,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_1": {
  "file": "man_at_arms_red_idle_d3_1.png",
  "fill": 0.2432,
  "fp_cx": 83.62,
  "fp_cy": 126.74,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_2": {
  "file": "man_at_arms_red_idle_d3_2.png",
  "fill": 0.2432,
  "fp_cx": 83.64,
  "fp_cy": 126.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_3": {
  "file": "man_at_arms_red_idle_d3_3.png",
  "fill": 0.2434,
  "fp_cx": 83.64,
  "fp_cy": 126.84,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_4": {
  "file": "man_at_arms_red_idle_d3_4.png",
  "fill": 0.2434,
  "fp_cx": 83.64,
  "fp_cy": 126.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d3_5": {
  "file": "man_at_arms_red_idle_d3_5.png",
  "fill": 0.2432,
  "fp_cx": 83.62,
  "fp_cy": 126.74,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4": {
  "clip": "idle",
  "dir": 4,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d4_0.png",
   "man_at_arms_red_idle_d4_1.png",
   "man_at_arms_red_idle_d4_2.png",
   "man_at_arms_red_idle_d4_3.png",
   "man_at_arms_red_idle_d4_4.png",
   "man_at_arms_red_idle_d4_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d4_0": {
  "file": "man_at_arms_red_idle_d4_0.png",
  "fill": 0.1941,
  "fp_cx": 78.86,
  "fp_cy": 128.2,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_1": {
  "file": "man_at_arms_red_idle_d4_1.png",
  "fill": 0.1952,
  "fp_cx": 79.04,
  "fp_cy": 128.26,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_2": {
  "file": "man_at_arms_red_idle_d4_2.png",
  "fill": 0.195,
  "fp_cx": 79.14,
  "fp_cy": 128.32,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_3": {
  "file": "man_at_arms_red_idle_d4_3.png",
  "fill": 0.1958,
  "fp_cx": 79.18,
  "fp_cy": 128.32,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_4": {
  "file": "man_at_arms_red_idle_d4_4.png",
  "fill": 0.195,
  "fp_cx": 79.14,
  "fp_cy": 128.32,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d4_5": {
  "file": "man_at_arms_red_idle_d4_5.png",
  "fill": 0.1954,
  "fp_cx": 79.04,
  "fp_cy": 128.26,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5": {
  "clip": "idle",
  "dir": 5,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d5_0.png",
   "man_at_arms_red_idle_d5_1.png",
   "man_at_arms_red_idle_d5_2.png",
   "man_at_arms_red_idle_d5_3.png",
   "man_at_arms_red_idle_d5_4.png",
   "man_at_arms_red_idle_d5_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d5_0": {
  "file": "man_at_arms_red_idle_d5_0.png",
  "fill": 0.1632,
  "fp_cx": 80.42,
  "fp_cy": 129.12,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_1": {
  "file": "man_at_arms_red_idle_d5_1.png",
  "fill": 0.1647,
  "fp_cx": 80.64,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_2": {
  "file": "man_at_arms_red_idle_d5_2.png",
  "fill": 0.1647,
  "fp_cx": 80.78,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_3": {
  "file": "man_at_arms_red_idle_d5_3.png",
  "fill": 0.1645,
  "fp_cx": 80.84,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_4": {
  "file": "man_at_arms_red_idle_d5_4.png",
  "fill": 0.1647,
  "fp_cx": 80.78,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d5_5": {
  "file": "man_at_arms_red_idle_d5_5.png",
  "fill": 0.1647,
  "fp_cx": 80.64,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6": {
  "clip": "idle",
  "dir": 6,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d6_0.png",
   "man_at_arms_red_idle_d6_1.png",
   "man_at_arms_red_idle_d6_2.png",
   "man_at_arms_red_idle_d6_3.png",
   "man_at_arms_red_idle_d6_4.png",
   "man_at_arms_red_idle_d6_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d6_0": {
  "file": "man_at_arms_red_idle_d6_0.png",
  "fill": 0.2436,
  "fp_cx": 73.4,
  "fp_cy": 127.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_1": {
  "file": "man_at_arms_red_idle_d6_1.png",
  "fill": 0.2417,
  "fp_cx": 73.56,
  "fp_cy": 127.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_2": {
  "file": "man_at_arms_red_idle_d6_2.png",
  "fill": 0.2404,
  "fp_cx": 73.64,
  "fp_cy": 127.36,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_3": {
  "file": "man_at_arms_red_idle_d6_3.png",
  "fill": 0.2396,
  "fp_cx": 73.68,
  "fp_cy": 127.34,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_4": {
  "file": "man_at_arms_red_idle_d6_4.png",
  "fill": 0.2404,
  "fp_cx": 73.64,
  "fp_cy": 127.36,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d6_5": {
  "file": "man_at_arms_red_idle_d6_5.png",
  "fill": 0.2413,
  "fp_cx": 73.56,
  "fp_cy": 127.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7": {
  "clip": "idle",
  "dir": 7,
  "duration": 2.5,
  "files": [
   "man_at_arms_red_idle_d7_0.png",
   "man_at_arms_red_idle_d7_1.png",
   "man_at_arms_red_idle_d7_2.png",
   "man_at_arms_red_idle_d7_3.png",
   "man_at_arms_red_idle_d7_4.png",
   "man_at_arms_red_idle_d7_5.png"
  ],
  "fps": 2.4,
  "frames": 6,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_idle_d7_0": {
  "file": "man_at_arms_red_idle_d7_0.png",
  "fill": 0.2693,
  "fp_cx": 60.4,
  "fp_cy": 127.88,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_1": {
  "file": "man_at_arms_red_idle_d7_1.png",
  "fill": 0.2687,
  "fp_cx": 60.38,
  "fp_cy": 127.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_2": {
  "file": "man_at_arms_red_idle_d7_2.png",
  "fill": 0.2681,
  "fp_cx": 60.36,
  "fp_cy": 127.7,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_3": {
  "file": "man_at_arms_red_idle_d7_3.png",
  "fill": 0.2677,
  "fp_cx": 60.36,
  "fp_cy": 127.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_4": {
  "file": "man_at_arms_red_idle_d7_4.png",
  "fill": 0.2679,
  "fp_cx": 60.36,
  "fp_cy": 127.7,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_idle_d7_5": {
  "file": "man_at_arms_red_idle_d7_5.png",
  "fill": 0.2689,
  "fp_cx": 60.38,
  "fp_cy": 127.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0": {
  "clip": "walk",
  "dir": 0,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d0_0.png",
   "man_at_arms_red_walk_d0_1.png",
   "man_at_arms_red_walk_d0_2.png",
   "man_at_arms_red_walk_d0_3.png",
   "man_at_arms_red_walk_d0_4.png",
   "man_at_arms_red_walk_d0_5.png",
   "man_at_arms_red_walk_d0_6.png",
   "man_at_arms_red_walk_d0_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d0_0": {
  "file": "man_at_arms_red_walk_d0_0.png",
  "fill": 0.2569,
  "fp_cx": 65.02,
  "fp_cy": 129.38,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_1": {
  "file": "man_at_arms_red_walk_d0_1.png",
  "fill": 0.2649,
  "fp_cx": 68.3,
  "fp_cy": 131.22,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_2": {
  "file": "man_at_arms_red_walk_d0_2.png",
  "fill": 0.2456,
  "fp_cx": 69.48,
  "fp_cy": 130.6,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_3": {
  "file": "man_at_arms_red_walk_d0_3.png",
  "fill": 0.2355,
  "fp_cx": 64.32,
  "fp_cy": 126.06,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_4": {
  "file": "man_at_arms_red_walk_d0_4.png",
  "fill": 0.2419,
  "fp_cx": 68.34,
  "fp_cy": 126.74,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_5": {
  "file": "man_at_arms_red_walk_d0_5.png",
  "fill": 0.2552,
  "fp_cx": 72.34,
  "fp_cy": 128.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_6": {
  "file": "man_at_arms_red_walk_d0_6.png",
  "fill": 0.2579,
  "fp_cx": 70.52,
  "fp_cy": 128.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d0_7": {
  "file": "man_at_arms_red_walk_d0_7.png",
  "fill": 0.2622,
  "fp_cx": 64.96,
  "fp_cy": 126.92,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1": {
  "clip": "walk",
  "dir": 1,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d1_0.png",
   "man_at_arms_red_walk_d1_1.png",
   "man_at_arms_red_walk_d1_2.png",
   "man_at_arms_red_walk_d1_3.png",
   "man_at_arms_red_walk_d1_4.png",
   "man_at_arms_red_walk_d1_5.png",
   "man_at_arms_red_walk_d1_6.png",
   "man_at_arms_red_walk_d1_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d1_0": {
  "file": "man_at_arms_red_walk_d1_0.png",
  "fill": 0.1954,
  "fp_cx": 62.78,
  "fp_cy": 133.16,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_1": {
  "file": "man_at_arms_red_walk_d1_1.png",
  "fill": 0.1933,
  "fp_cx": 67.66,
  "fp_cy": 133.3,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_2": {
  "file": "man_at_arms_red_walk_d1_2.png",
  "fill": 0.2006,
  "fp_cx": 67.64,
  "fp_cy": 132.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_3": {
  "file": "man_at_arms_red_walk_d1_3.png",
  "fill": 0.1985,
  "fp_cx": 57.58,
  "fp_cy": 131.06,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_4": {
  "file": "man_at_arms_red_walk_d1_4.png",
  "fill": 0.1865,
  "fp_cx": 61.38,
  "fp_cy": 130.12,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_5": {
  "file": "man_at_arms_red_walk_d1_5.png",
  "fill": 0.2006,
  "fp_cx": 66.64,
  "fp_cy": 129.92,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_6": {
  "file": "man_at_arms_red_walk_d1_6.png",
  "fill": 0.2149,
  "fp_cx": 65.42,
  "fp_cy": 130.6,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d1_7": {
  "file": "man_at_arms_red_walk_d1_7.png",
  "fill": 0.2118,
  "fp_cx": 59.24,
  "fp_cy": 131.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2": {
  "clip": "walk",
  "dir": 2,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d2_0.png",
   "man_at_arms_red_walk_d2_1.png",
   "man_at_arms_red_walk_d2_2.png",
   "man_at_arms_red_walk_d2_3.png",
   "man_at_arms_red_walk_d2_4.png",
   "man_at_arms_red_walk_d2_5.png",
   "man_at_arms_red_walk_d2_6.png",
   "man_at_arms_red_walk_d2_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d2_0": {
  "file": "man_at_arms_red_walk_d2_0.png",
  "fill": 0.1971,
  "fp_cx": 69.56,
  "fp_cy": 130.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_1": {
  "file": "man_at_arms_red_walk_d2_1.png",
  "fill": 0.1943,
  "fp_cx": 73.22,
  "fp_cy": 128.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_2": {
  "file": "man_at_arms_red_walk_d2_2.png",
  "fill": 0.2133,
  "fp_cx": 72.0,
  "fp_cy": 128.2,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_3": {
  "file": "man_at_arms_red_walk_d2_3.png",
  "fill": 0.2097,
  "fp_cx": 62.94,
  "fp_cy": 130.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_4": {
  "file": "man_at_arms_red_walk_d2_4.png",
  "fill": 0.202,
  "fp_cx": 64.28,
  "fp_cy": 128.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_5": {
  "file": "man_at_arms_red_walk_d2_5.png",
  "fill": 0.2002,
  "fp_cx": 67.72,
  "fp_cy": 126.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_6": {
  "file": "man_at_arms_red_walk_d2_6.png",
  "fill": 0.1981,
  "fp_cx": 67.82,
  "fp_cy": 127.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d2_7": {
  "file": "man_at_arms_red_walk_d2_7.png",
  "fill": 0.1979,
  "fp_cx": 64.64,
  "fp_cy": 130.46,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3": {
  "clip": "walk",
  "dir": 3,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d3_0.png",
   "man_at_arms_red_walk_d3_1.png",
   "man_at_arms_red_walk_d3_2.png",
   "man_at_arms_red_walk_d3_3.png",
   "man_at_arms_red_walk_d3_4.png",
   "man_at_arms_red_walk_d3_5.png",
   "man_at_arms_red_walk_d3_6.png",
   "man_at_arms_red_walk_d3_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d3_0": {
  "file": "man_at_arms_red_walk_d3_0.png",
  "fill": 0.2299,
  "fp_cx": 82.96,
  "fp_cy": 127.02,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_1": {
  "file": "man_at_arms_red_walk_d3_1.png",
  "fill": 0.2292,
  "fp_cx": 83.24,
  "fp_cy": 124.58,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_2": {
  "file": "man_at_arms_red_walk_d3_2.png",
  "fill": 0.2265,
  "fp_cx": 81.54,
  "fp_cy": 124.6,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_3": {
  "file": "man_at_arms_red_walk_d3_3.png",
  "fill": 0.2251,
  "fp_cx": 78.78,
  "fp_cy": 129.62,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_4": {
  "file": "man_at_arms_red_walk_d3_4.png",
  "fill": 0.2297,
  "fp_cx": 76.88,
  "fp_cy": 127.72,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_5": {
  "file": "man_at_arms_red_walk_d3_5.png",
  "fill": 0.2257,
  "fp_cx": 76.48,
  "fp_cy": 125.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_6": {
  "file": "man_at_arms_red_walk_d3_6.png",
  "fill": 0.2189,
  "fp_cx": 77.84,
  "fp_cy": 125.7,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d3_7": {
  "file": "man_at_arms_red_walk_d3_7.png",
  "fill": 0.2276,
  "fp_cx": 79.52,
  "fp_cy": 128.8,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4": {
  "clip": "walk",
  "dir": 4,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d4_0.png",
   "man_at_arms_red_walk_d4_1.png",
   "man_at_arms_red_walk_d4_2.png",
   "man_at_arms_red_walk_d4_3.png",
   "man_at_arms_red_walk_d4_4.png",
   "man_at_arms_red_walk_d4_5.png",
   "man_at_arms_red_walk_d4_6.png",
   "man_at_arms_red_walk_d4_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d4_0": {
  "file": "man_at_arms_red_walk_d4_0.png",
  "fill": 0.1944,
  "fp_cx": 78.98,
  "fp_cy": 128.72,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_1": {
  "file": "man_at_arms_red_walk_d4_1.png",
  "fill": 0.1956,
  "fp_cx": 75.7,
  "fp_cy": 126.88,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_2": {
  "file": "man_at_arms_red_walk_d4_2.png",
  "fill": 0.1879,
  "fp_cx": 74.52,
  "fp_cy": 127.5,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_3": {
  "file": "man_at_arms_red_walk_d4_3.png",
  "fill": 0.1881,
  "fp_cx": 79.68,
  "fp_cy": 132.02,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_4": {
  "file": "man_at_arms_red_walk_d4_4.png",
  "fill": 0.1883,
  "fp_cx": 75.66,
  "fp_cy": 131.36,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_5": {
  "file": "man_at_arms_red_walk_d4_5.png",
  "fill": 0.1873,
  "fp_cx": 71.66,
  "fp_cy": 129.62,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_6": {
  "file": "man_at_arms_red_walk_d4_6.png",
  "fill": 0.2066,
  "fp_cx": 73.48,
  "fp_cy": 129.58,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d4_7": {
  "file": "man_at_arms_red_walk_d4_7.png",
  "fill": 0.2135,
  "fp_cx": 79.04,
  "fp_cy": 131.18,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5": {
  "clip": "walk",
  "dir": 5,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d5_0.png",
   "man_at_arms_red_walk_d5_1.png",
   "man_at_arms_red_walk_d5_2.png",
   "man_at_arms_red_walk_d5_3.png",
   "man_at_arms_red_walk_d5_4.png",
   "man_at_arms_red_walk_d5_5.png",
   "man_at_arms_red_walk_d5_6.png",
   "man_at_arms_red_walk_d5_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d5_0": {
  "file": "man_at_arms_red_walk_d5_0.png",
  "fill": 0.1647,
  "fp_cx": 81.22,
  "fp_cy": 129.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_1": {
  "file": "man_at_arms_red_walk_d5_1.png",
  "fill": 0.1738,
  "fp_cx": 76.34,
  "fp_cy": 129.3,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_2": {
  "file": "man_at_arms_red_walk_d5_2.png",
  "fill": 0.1806,
  "fp_cx": 76.36,
  "fp_cy": 130.14,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_3": {
  "file": "man_at_arms_red_walk_d5_3.png",
  "fill": 0.1775,
  "fp_cx": 86.42,
  "fp_cy": 131.52,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_4": {
  "file": "man_at_arms_red_walk_d5_4.png",
  "fill": 0.1601,
  "fp_cx": 82.62,
  "fp_cy": 132.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_5": {
  "file": "man_at_arms_red_walk_d5_5.png",
  "fill": 0.1599,
  "fp_cx": 77.36,
  "fp_cy": 132.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_6": {
  "file": "man_at_arms_red_walk_d5_6.png",
  "fill": 0.1807,
  "fp_cx": 78.58,
  "fp_cy": 132.0,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d5_7": {
  "file": "man_at_arms_red_walk_d5_7.png",
  "fill": 0.1856,
  "fp_cx": 84.76,
  "fp_cy": 131.16,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6": {
  "clip": "walk",
  "dir": 6,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d6_0.png",
   "man_at_arms_red_walk_d6_1.png",
   "man_at_arms_red_walk_d6_2.png",
   "man_at_arms_red_walk_d6_3.png",
   "man_at_arms_red_walk_d6_4.png",
   "man_at_arms_red_walk_d6_5.png",
   "man_at_arms_red_walk_d6_6.png",
   "man_at_arms_red_walk_d6_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d6_0": {
  "file": "man_at_arms_red_walk_d6_0.png",
  "fill": 0.2294,
  "fp_cx": 74.44,
  "fp_cy": 127.44,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_1": {
  "file": "man_at_arms_red_walk_d6_1.png",
  "fill": 0.2431,
  "fp_cx": 70.78,
  "fp_cy": 129.08,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_2": {
  "file": "man_at_arms_red_walk_d6_2.png",
  "fill": 0.2514,
  "fp_cx": 72.0,
  "fp_cy": 129.68,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_3": {
  "file": "man_at_arms_red_walk_d6_3.png",
  "fill": 0.2348,
  "fp_cx": 81.06,
  "fp_cy": 127.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_4": {
  "file": "man_at_arms_red_walk_d6_4.png",
  "fill": 0.2386,
  "fp_cx": 79.72,
  "fp_cy": 129.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_5": {
  "file": "man_at_arms_red_walk_d6_5.png",
  "fill": 0.233,
  "fp_cx": 76.28,
  "fp_cy": 131.1,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_6": {
  "file": "man_at_arms_red_walk_d6_6.png",
  "fill": 0.213,
  "fp_cx": 76.18,
  "fp_cy": 130.2,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d6_7": {
  "file": "man_at_arms_red_walk_d6_7.png",
  "fill": 0.2224,
  "fp_cx": 79.36,
  "fp_cy": 127.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7": {
  "clip": "walk",
  "dir": 7,
  "duration": 1.6667,
  "files": [
   "man_at_arms_red_walk_d7_0.png",
   "man_at_arms_red_walk_d7_1.png",
   "man_at_arms_red_walk_d7_2.png",
   "man_at_arms_red_walk_d7_3.png",
   "man_at_arms_red_walk_d7_4.png",
   "man_at_arms_red_walk_d7_5.png",
   "man_at_arms_red_walk_d7_6.png",
   "man_at_arms_red_walk_d7_7.png"
  ],
  "fps": 4.8,
  "frames": 8,
  "group": "animation",
  "team": "red"
 },
 "man_at_arms_red_walk_d7_0": {
  "file": "man_at_arms_red_walk_d7_0.png",
  "fill": 0.2589,
  "fp_cx": 61.04,
  "fp_cy": 127.48,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_1": {
  "file": "man_at_arms_red_walk_d7_1.png",
  "fill": 0.2685,
  "fp_cx": 60.76,
  "fp_cy": 129.94,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_2": {
  "file": "man_at_arms_red_walk_d7_2.png",
  "fill": 0.2631,
  "fp_cx": 62.46,
  "fp_cy": 129.92,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_3": {
  "file": "man_at_arms_red_walk_d7_3.png",
  "fill": 0.2537,
  "fp_cx": 65.22,
  "fp_cy": 124.88,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_4": {
  "file": "man_at_arms_red_walk_d7_4.png",
  "fill": 0.2558,
  "fp_cx": 67.12,
  "fp_cy": 126.78,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_5": {
  "file": "man_at_arms_red_walk_d7_5.png",
  "fill": 0.2604,
  "fp_cx": 67.52,
  "fp_cy": 129.42,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_6": {
  "file": "man_at_arms_red_walk_d7_6.png",
  "fill": 0.2612,
  "fp_cx": 66.16,
  "fp_cy": 128.82,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 },
 "man_at_arms_red_walk_d7_7": {
  "file": "man_at_arms_red_walk_d7_7.png",
  "fill": 0.2589,
  "fp_cx": 64.48,
  "fp_cy": 125.72,
  "fp_w": 51.42,
  "h": 144,
  "w": 144
 }
});
