#!/usr/bin/env python3
"""Copy a baked directional unit into the web game.

    python3 art/pipeline/install_unit_sprites.py art/out/man_at_arms/sprites@2x man_at_arms

Copies every PNG in SRC into ios/WebGame/sprites/ and writes
ios/WebGame/sprites/manifest_<unit>.js, which merges SRC/manifest_snippet.json into
window.POCKET_EMPIRES_SPRITES. The snippet stays in its own file instead of being folded into
manifest.js because scripts/bake_zeroad_art.py regenerates manifest.js from scratch and would drop
it. Rerunning with a newer bake (e.g. man_at_arms_v2) replaces the PNGs and the manifest in place,
because the keys are the same.

After adding or renaming files, re-run CMake (with the OE_BUNDLE_ID/OE_DEVELOPMENT_TEAM flags):
the app bundle's file list is globbed at configure time.
"""
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / "ios" / "WebGame" / "sprites"


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, unit = Path(sys.argv[1]).resolve(), sys.argv[2]
    snippet = json.loads((src / "manifest_snippet.json").read_text())
    # Drop stale frames from an earlier bake so a smaller set does not leave orphans behind.
    for old in DEST.glob(f"{unit}_*.png"):
        old.unlink()
    pngs = sorted(src.glob(f"{unit}_*.png"))
    for p in pngs:
        shutil.copy2(p, DEST / p.name)
    missing = [v["file"] for v in snippet.values()
               if isinstance(v, dict) and "file" in v and not (DEST / v["file"]).exists()]
    if missing:
        sys.exit(f"manifest names {len(missing)} files that were not baked, e.g. {missing[:3]}")
    body = json.dumps(snippet, indent=1, sort_keys=True)
    (DEST / f"manifest_{unit}.js").write_text(
        f"/* Generated by art/pipeline/install_unit_sprites.py from {src.relative_to(ROOT)} */\n"
        "window.POCKET_EMPIRES_SPRITES = Object.assign(window.POCKET_EMPIRES_SPRITES || {}, "
        f"{body});\n")
    print(f"installed {len(pngs)} sprites and manifest_{unit}.js")


if __name__ == "__main__":
    main()
